### ISSUE TITLE
Nemo icon dispaered

### ISSUE THREAD

**Issue by PowaBanga** [jnsh/arc-theme#102]
Please add the following information:

- Distribution and version.
- Archlinux (last update)
 
- Versions for the affected applications/desktops/tookits.
- nemo 4.8.2

- Installation method (package or compiled manually).
From official archlinux repository ![arc-icon-theme]([https://www.archlinux.org/packages/community/any/arc-icon-theme/)
and from [AUR repository](https://aur.archlinux.org/packages/arc-icon-theme-git/)

Since my update the 19/11/2020, 
the folder icon for nemo do not appeart normaly since yesterday, apparently after a nemo update. ![](https://i.imgur.com/iUlu7SG.png) it is not normal i think...

So,
before my system update, i was on arc-gtk-theme with cinnamon.
The folder icon of nemo application in menu and in taskbar was the arc icon theme (figure C on picture)
Since the update (pacman -Syu), it has been change by the figure (b)

So, for me, the figure (b) is really ugly, I do not understand why my nemo icon was changed, and if it's because arc icon theme do not provide application icons, so i do not understand why it is not the icon (a) who is used, because this icon should be the default adwaita icon theme...

![](https://i.imgur.com/u7ZCHj1.png)

After speaking about that in [archlinux bugtracker](https://bugs.archlinux.org/task/68781?only_watched=1&type%5B0%5D=&sev%5B0%5D=&due%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&reported%5B0%5D=)

it seem that this is due from a change to nemo https://github.com/linuxmint/nemo/pull/2514

**Comment by jnsh** [comment]
Sorry, but the Arc icon theme is not maintained here (or anywhere else that I know of), so this is the wrong place for the issue report.

The Arc icon theme project was barely started before it got abandonded, and is therefore **extremely** unfinished. Personally I'd strongly discourage anyone from using it.

FWIW, If you want to use the old icon for Nemo, you can alter the `.desktop` file yourself to use the `folder` icon as it did before.
