### ISSUE TITLE
Certain tray icons in MATE are too small

### ISSUE THREAD

**Issue by Anonymous1157** [jnsh/arc-theme#104]
It's exactly what it says in the title. I didn't find this problem in Arc at first, rather this issue has been happening for many years with every Arc-derived theme I have ever tried. I just now realized the connection and, yup, it happens in the real Arc as well.

I'm using Gentoo ~amd64 and I installed 20201013 from the package manager. I'm not sure what other package version details you would need since this has been happening for so long that I'm not sure it's relevant. I know I could see the issue in Gnome-Xpro, an Arc derived theme, possibly in 2017 or 2018.

Again, to be clear, this happens in every Arc theme, including Arc itself, and does not happen in themes made from scratch or derived from a different lineage.

This is how my tray looks in Arc:
![image](https://user-images.githubusercontent.com/8900271/103134151-1ad5af00-467d-11eb-92e8-911a3270354f.png)

This is how it looks in Cloudy:
![image](https://user-images.githubusercontent.com/8900271/103133841-cc271580-467a-11eb-9a2c-bc198a3c2985.png)

This is the expected behavior in Adwaita:
![image](https://user-images.githubusercontent.com/8900271/103133821-a13cc180-467a-11eb-9d91-a456e2f9bc46.png)

Changing the size of the panel does not make a difference. The icons that are smaller will never get any bigger no matter how large I resize it. The icon theme doesn't make a difference either.

**Comment by jnsh** [comment]
Thank you for the report. This should be fixed with https://github.com/jnsh/arc-theme/commit/aab9ac9e8557def9accea5153e26c8cf51551f04, but let me know if there are any remaining issues.
