### ISSUE TITLE
xfce4 4.16 not work

### ISSUE THREAD

**Issue by JoveYu** [jnsh/arc-theme#105]

**Comment by jnsh** [comment]
Please explain what's not working. I do not notice any issues myself.

**Comment by JoveYu** [comment]
![截图_2020-12-26_00-34-33](https://user-images.githubusercontent.com/1973603/103138940-350d9c80-4712-11eb-9516-8de2c947d52a.png)

thunar in xfce4 4.16

**Comment by jnsh** [comment]
Sorry but I can't reproduce the problem.

Does this happen with other GTK themes, e.g. Adwaita? If it does, I'd suggest reporting this as an issue for thunar.

**Comment by JoveYu** [comment]
okay thank you
