### ISSUE TITLE
White spot at the right side of the toolbar in thunar 

### ISSUE THREAD

**Issue by malnvenshorn** [jnsh/arc-theme#107]
After updating Thunar from version 1.8.16 to 4.16.0. There is a white spot at the right edge of the toolbar. This spot exists with Arc, Arc-Darker, Arc-Dark. The difference is only the color. I haven't noticed this in other application so far.

I'm using Arch Linux with Xfce 4.16 with the latest release of this theme (20201013)

![Bildschirmfoto_2020-12-26_19-45-44](https://user-images.githubusercontent.com/13801805/103157571-4dce8e80-47b4-11eb-9e74-20d5c7a4b429.png)

**Comment by jnsh** [comment]
Thanks for the report. This is an [upstream issue](https://gitlab.xfce.org/xfce/thunar/-/issues/448), but I'll apply a workaround if it won't get fixed shortly.

The workaround is already being worked on in https://github.com/jnsh/arc-theme/pull/106

**Comment by malnvenshorn** [comment]
Thanks for the fast reply. I haven't looked at the pull requests. A workaround would be nice until it gets fixed upstream.

**Comment by jnsh** [comment]
Until there's some kind of permanent fix, you can work around this yourself by adding one of the following one-liners (based on the aforementioned pull request) to your user's `~/.config/gtk-3.0/gtk.css` file.

For Arc and Arc-Lighter:
`.thunar grid > box { background-color: #e7e8eb; }`

For Arc-Dark and Arc-Darker
`.thunar grid > box { background-color: #2f343f; }`

**Comment by jnsh** [comment]
Thunar 4.16.1 has been released, and this should be fixed with it. Closing.
