### ISSUE TITLE
Could not determine GTK3 version.

### ISSUE THREAD

**Issue by TheNewJudas** [jnsh/arc-theme#108]
`configure: error: Could not determine GTK3 version. Install GTK3 (and its development files), or use the --with-gtk3=<version> option. Alternatively you can choose to not build the GTK3 theme with --disable-gtk3 option.
`

Happening on OpenSUSE Tumbleweed. 
I'm sure there is an easy way around this but if so, it could've been added to the INSTALL.md file.

**Comment by jnsh** [comment]
Well, the way around is explained in the very error message you posted:
> configure: error: Could not determine GTK3 version. **Install GTK3 (and its development files), or use the --with-gtk3=<version> option. Alternatively you can choose to not build the GTK3 theme with --disable-gtk3 option.** 

This is also explained in detail in the [versioned themes](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#versioned-themes) section of the INSTALL.md.

I'm happy to hear any possible suggestions for making this even more clearer.

**Comment by jnsh** [comment]
Closing, since there hasn't been any follow ups.

I hope you got it figured out. Let me know if you didn't, or if you encounter any other issues.
