### ISSUE TITLE
Default font too gray/low contrast

### ISSUE THREAD

**Issue by wooque** [jnsh/arc-theme#110]
### Details
- Distribution and version: Arch Linux
- Arc-theme version: 20201013-2

Default font color is too gray/low contrast and bit hard to read. Please make default color a bit blacker.

![Screenshot from 2021-01-14 13-13-01](https://user-images.githubusercontent.com/1936195/104589737-9a4a1300-566a-11eb-9323-c8ee12fcd9c7.png)

**Comment by jnsh** [comment]
Sorry but the text color won't be changed.

While I can see why some might prefer more contrast (especially when using older / low contrast monitor) and I've seen [requests for this on the original project](https://github.com/horst3180/arc-theme/issues/406), this fork is strictly for maintenance of the theme, and the original design won't be altered here unless it's absolutely necessary.

If you don't mind compiling the theme yourself, you can change the text/foreground color for light variants quite easily by running something like the following from the base source directory before compilation:

```
find common -name "*" -type f -exec sed -i 's/'5C616C'/'464952'/gI' {}  \;
```

Change `464952` to the hex value of your preferred text color, if that's not dark enough for you.

Note that doing this **after** the compilation, as suggested in the aforementioned issue, won't change the foreground color on all occasions throughout the SASS based themes.

**Comment by jnsh** [comment]
Additional note for Arch Linux users: if you use e.g. [arc-gtk-theme-git](https://aur.archlinux.org/packages/arc-gtk-theme-git/) AUR package, or any other PKGBUILD for compilation. The color can be changed easily during the `makepkg` build by adding e.g. the following to the PKGBUILD:
```
prepare() {
  cd "${srcdir}/${_pkgname}"
  find common -name "*" -type f -exec sed -i 's/'5C616C'/'464952'/gI' {}  \;
}
```

**Comment by killajoe** [comment]
> Additional note for Arch Linux users: if you use [arc-gtk-theme-git](https://aur.archlinux.org/packages/arc-gtk-theme-git/) AUR package, or any other PKGBUILD for compilation. The color can be changed easily during the `makepkg` build by adding e.g. the following to the PKGBUILD:
> 
> ```
> prepare() {
>   cd "${srcdir}/${_pkgname}"
>   find common -name "*" -type f -exec sed -i 's/'5C616C'/'464952'/gI' {}  \;
> }
> ```

```
prepare() {
  cd "${srcdir}/${_pkgname}-${pkgver}"
  find common -name "*" -type f -exec sed -i 's/'5C616C'/'464952'/gI' {}  \;
}
```
to take the PKGBUILD from community

**Comment by andrei-papou** [comment]
@jnsh releasing `High-Contrast` versions of the theme might be a good solution for the issue. The original design won't be changed, there will be just 4 more versions of the theme. I think adding `Lighter` version was a modification of a similar kind. What do you think?

**Comment by jnsh** [comment]
@andrei-papou Sorry, but no. The current text color is part of the original design, so this would be a distinct change to it. The addition of the lighter variant was not a comparable change, since it simply applied the existing light design over the remaining dark elements on the main light variant.

If anyone finds this important, it should be fairly simple to create fork that applies a single commit to change the text color, and that shouldn't require a lot of maintenance either. Also a separate fork would be considerably simpler task than including the additional variants to the main theme.
