### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheGrandFinale2001** [jnsh/arc-theme#111]
This may be a long shot but I thought I would ask anyways.  You may or may not use Compiz but I still love it and use it and I was wondering if you could make an Emerald theme?  I know you can use the gtk decorator that doesn't always work well.

Thanks for keeping the theme alive!!

**Comment by jnsh** [comment]
Thanks for the suggestion.

The number of themes maintained here is already a bit overwhelming, so I'm not very favorable for further additions, especially with the ongoing workload on getting and keeping the existing themes in proper shape.

If I'm not mistaken, the compiz GTK decorator uses metacity themes, which is already supported in Arc. If there are issues on compiz resulting from bugs in the theme, I can certainly look at fixing those. If the problems result from the gtk-decorator itself, it would be best to get those issues fixed upstream.

**Comment by jnsh** [comment]
Closing, since there hasn't been additional comments in quite a while.

As explained above, adding emerald theme doesn't seem prudent. However, please let me know if there's anything to fix or that could be improved in the metacity/gtk decorator theme.
