### ISSUE TITLE
(Meson) Installation: Arc/gtk-2.0/assets: No such file or directory

### ISSUE THREAD

**Issue by ghost** [jnsh/arc-theme#112]
Hello,

when i try to build your theme with the new meson build system on FreeBSD it fails at the end on install:

`install: /usr/ports/x11-themes/gtk-arc-themes/work/stage/usr/local/share/themes/Arc/gtk-2.0/assets: No such file or directory`

[buildlog](https://gist.github.com/LastTrainToLondon/c7747c90bcb1bcedaeddfd8c0085ed63)

**Comment by jnsh** [comment]
Thank you for testing the meson build, and letting me know about the problem.

Unfortunately, I'm unsure what's going wrong here. Could you try building the theme manually without using ports? just to make sure this doesn't result from the build script.

**Comment by LastTrainToLondon** [comment]
Unfortunately the same error with the same information.

**Comment by LastTrainToLondon** [comment]
Using GNU's install and cp fixed that. Update can now be submitted to ports Thanks for answering!

**Comment by jnsh** [comment]
Closing, as the requirement for GNU install was dropped with recent updates. So there shouldn't be issues when compiling in *BSD any more.
