### ISSUE TITLE
Feature: dark Xfce panel variation

### ISSUE THREAD

**Issue by mki77** [jnsh/arc-theme#114]
Is possible to get the dark Xfce panel in the Arc Lighter version? Can you tell me what I need to change?

**Comment by jnsh** [comment]
Xfce panel should be dark for the base light "Arc" variant, and every other variant apart from Arc-Lighter.

If you want to change it's styling, look at `_applications.scss` for the GTK3 theme.

**Comment by mki77** [comment]
Is there a way to not have compiled gtk3 css resources?

**Comment by jnsh** [comment]
If you don't want to recompile the theme, you can try injecting CSS via `~/.config/gtk-3.0/gtk.css`.

**Comment by mki77** [comment]
Thanks, I'll try like this.
