### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by diego-ninja** [jnsh/arc-theme#116]
It would be nice to get a Nord variant of the theme (https://www.nordtheme.com/) or even better to have the possibility of apply differente color schemes and generate a new theme variant, maybe extrating global palette to a common .scss file and replacing that file.

Just an idea.

**Comment by jnsh** [comment]
Thanks for the suggestion, but I won't be adding any more variants. Any color variations should be implemented and maintained in separate forks.

It would be nice to have a built in possibility to adjust the theme's colors, but there's no sensible way to do it (most of the supported themes don't use SASS, so simply modifying a global `_colors.scss` is not an option).

I have plans for a separate script that could be used to adjust the theme's colors, and should be helpful in creating separate color variant forks, but there's a lot of more urgent work I must focus on before looking into that.

**Comment by TRPB** [comment]
FYI, if anyone wants to swap out the Arc colours with Nord colours, it's pretty easy. Run this prior to building:

```
# Night 1
find . -name "*" -type f -exec sed -i 's/'2F343F'/'2e3440'/gI' {} \;

# Night 2
find . -name "*" -type f -exec sed -i 's/'383C4A'/'3b4252'/gI' {} \;

# Night 3
find . -name "*" -type f -exec sed -i 's/'404552'/'434c5e'/gI' {} \;

# Night 4
find . -name "*" -type f -exec sed -i 's/'565965'/'4c566a'/gI' {} \;


# highlight color
find . -name "*" -type f -exec sed -i 's/'5294E2'/'5e81ac'/gI' {} \;

```

then set the theme to Arc-Dark.
