### ISSUE TITLE
Menu item separators are not being displayed

### ISSUE THREAD

**Issue by jmgq** [jnsh/arc-theme#118]
As we can see in the following image, the separators that divide certain items in a menu are not showing:

![Incorrect](https://i.ibb.co/6rvSDBM/error.png)

For comparison, here it is how it looks like with the Adwaita theme:

![Correct](https://i.ibb.co/QPtRGSj/correct.png)

With the Arc theme, the 4 horizontal separators are missing.

This error happens with the 4 different versions of the theme: Arc, Arc-Dark, Arc-Darker and Arc-Lighter.

I have tested this in Xfce 4.16 in Debian Testing (bullseye), downloading the theme via apt (the version there is 20201013-2), as well as downloading the `master` branch of this repository and installing manually. I have also tried restarting, but that didn't help.

In case it's relevant, here is some additional info about my machine:
```
OS: Debian GNU/Linux bullseye/sid x86_64 
Kernel: 5.10.0-3-amd64
Resolution: 1920x1095
DE: Xfce 4.16
WM: Xfwm4
WM Theme: Arc
Theme: Arc [GTK2/3]
Icons: Tango [GTK2], Adwaita [GTK3]
```

**Comment by jnsh** [comment]
Thank you for the detailed report, but this is not an error. The menu separators were intentionally left out by the original designer since the first revision of the theme.

The visual design of the theme won't be altered in this fork, so the menu separators won't be added here either.

**Comment by jmgq** [comment]
Thanks clarifying, @jnsh. That's fair enough, in that case I'll close this issue.
