### ISSUE TITLE
meson_version is wrong

### ISSUE THREAD

**Issue by davekeogh** [jnsh/arc-theme#119]
The substring method that is being used in common/gtk-2.0/meson.build was not added until 0.56 (https://mesonbuild.com/Syntax.html#substring), but meson_version is '>= 0.50.0'.

Ubuntu 20.10, for instance, has meson 0.55.3. So the meson build is going to fail pretty much everywhere.

**Comment by jnsh** [comment]
Thank you for pointing this out.

My intention was to support meson versions starting from 0.50.0, as it seemed to be safe for most recent distribution releases, so using the `.substring()` method was a mistake. Meson usually prints out a clear warning if you use methods not supported by the targeted `meson_version`, but for some reason it doesn't do that here, and therefore this was left unnoticed.

I'll sort this out ASAP.

**Comment by jnsh** [comment]
This should be now fixed in `master`. Please let me know if you have any further issues.

Thanks again for the report.
