### ISSUE TITLE
Nautilus path bar has different styling when maximized

### ISSUE THREAD

**Issue by ariflukito** [jnsh/arc-theme#12]
Hi,

The Nautilus path bar has different styling when it's maximized or it's resized wide enough. The maximized style has a background and border around it. Probably it's a design decision since it's consistent with Adwaita. But it looks a bit odd for me.

![Screenshot from 2019-11-08 16-44-32](https://user-images.githubusercontent.com/5508660/68453997-59c35e00-024b-11ea-944b-4940d490c7c9.png)

![Screenshot from 2019-11-08 16-43-37](https://user-images.githubusercontent.com/5508660/68454007-6942a700-024b-11ea-8531-c6749d51e0b0.png)

Yaru theme has some discussions here https://github.com/ubuntu/yaru/issues/1304

- Distribution and version: Arch / GNOME 3.34.1
- Versions for the affected applications/desktops/tookits: Git Master

**Comment by jnsh** [comment]
Thank you for the report.

The border around the maximized path-bar is based on the default Nautilus design. I think it's necessary for distinguishing the path-bar area on the width-maximized mode, when it is centered on the header. The upstream discussions seem very scattered, but e.g. [this commit message](https://gitlab.gnome.org/GNOME/nautilus/commit/080400bd243ab86d82954eaff0c866c3ac97f3f2) states that the border is necessary.

Without the border, it seems like the path-bar buttons aren't aligned in any way, but placed pretty much randomly, as seen here:

![nautiluspathbar](https://user-images.githubusercontent.com/39574454/68522142-9d9c7e80-02b0-11ea-8711-e03b960d42ba.png)

Comparing side-by-side, I see that the buttons are different colors, which certainly looks inconsistent, and I can try to fix. Apart from that, did you have any suggestions for improvements, on more specific gripes about the current design?

**Comment by ariflukito** [comment]
Thank you for taking a look.

The only solution I can think of is to always show the border. However he did mentioned on the commit message you linked above, the border will only create visual noise on small windows.

![Screenshot from 2019-11-13 11-48-46](https://user-images.githubusercontent.com/5508660/68725986-3d8d3b80-0614-11ea-9200-e18c56d70f9a.png)

So I guess it's between whether you want a consistency at the cost of visual noise or a clean look.

Also I just noticed this, from time to time the borders on the path bar don't apply properly. If you see from the first image below looks like there's extra border applied. On the second image, the border on path bar missing. These are the steps to reproduce the problems:

1. open nautilus
2. double click header bar to maximize -> first image
3. double click header bar to unmaximize > second image

I don't know how to reproduce the second image reliably though.
If I refocus the window after changing focus to other window, the borders will redraw properly. Let me know if you want me to open separate issue. Thank you.

![Screenshot from 2019-11-13 13-09-11](https://user-images.githubusercontent.com/5508660/68727330-30724b80-0618-11ea-9e97-721a82981276.png)

![Screenshot from 2019-11-13 13-16-13](https://user-images.githubusercontent.com/5508660/68727414-729b8d00-0618-11ea-929f-83c0714d1584.png)

**Comment by jnsh** [comment]
I just pushed commit dbb546722c687fd40fb197f02bbebcb13e841426, that should improve the `width-maximized` look, by removing background color from the path-bar-box:
![nppupd](https://user-images.githubusercontent.com/39574454/68730683-27f92100-05d6-11ea-8b5f-1d2c47a9e9ee.png)

I'd prefer to follow the upstream design with this, and only have the border visible on the maximized path bar for now.

> Also I just noticed this, from time to time the borders on the path bar don't apply properly. If you see from the first image below looks like there's extra border applied. On the second image, the border on path bar missing.

This is not Arc theme specific issue, but should happen with most themes, including Adwaita. This is reported as an upstream nautilus bug [here](https://gitlab.gnome.org/GNOME/nautilus/issues/907).

**Comment by ariflukito** [comment]
Looks like upstream is moving to always show the background. There's an open merge request [here](https://gitlab.gnome.org/GNOME/nautilus/merge_requests/475). Anyway closing this for now. Thank you for your help.
