### ISSUE TITLE
[request] New release for Gnome 40? :)

### ISSUE THREAD

**Issue by francoism90** [jnsh/arc-theme#121]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts.
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details

Please add the following information:

- Arch Linux 20210127
- Gnome 40
- package
- 20210127

I have notice a lot of commits have been made after the January release. Could you please tag a new release? :)

**Comment by jnsh** [comment]
I will roll out a new release once the remaining issues in the GNOME Shell 40 theme port are sorted (hopefully soon), and I also hope it would receive some further user testing in case I've missed anything.

Until that happens, those users who want to help testing the updated shell theme have to build it from git themselves (or in case of Arch linux, you can install the `arc-gtk-theme-git` from AUR, although at this time you need to bump the gnome-shell version in the `PKGBUILD`).

If there's any kind imminent need for the new release with GNOME 40 support, e.g. for it to get packaged for specific distribution release until a packaging freeze starts, I'm asking for the packagers to let me know of any deadlines, and I can at least make a strong attempt to get the new release out in time.

**Comment by liamtimms** [comment]
@jnsh I have a machine set up for testing this if you like (using the current Arch build in [gnome-unstable] and the AUR arc-theme-git PKGBUILD). So far there's nothing obvious wrong but let me know if there's something specific you want users to test.

**Comment by jnsh** [comment]
@liamtimms There's nothing specific that should be tested, just open an issue about anything that looks wrong that you might notice, as usual.

The theme needs some rethinking with the redesigned overview, but there shouldn't be any major issues remaining. Biggest known "problem" are the workspace-background corners that don't really fit the Arc style, and can't be adjusted currently due to upstream limitations (there's a [proposal to fix this](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1779)).

**Comment by francoism90** [comment]
@jnsh If I'm not mistaken this has been discussed before, but I don't like the large(r) font-size in Gnome-Shell.

So far it seems to be running well on GS40 on gnome-unstable (arch).

**Comment by jnsh** [comment]
> @jnsh If I'm not mistaken this has been discussed before, but I don't like the large(r) font-size in Gnome-Shell.

The font size is very easy to adjust exactly to your liking by adjusting the font scaling factor. Refer to the earlier discussions [[1]](https://github.com/jnsh/arc-theme/issues/15) [[2]](https://github.com/jnsh/arc-theme/issues/77) for more details.

Also, please stay in topic in the issues. This has nothing to do with GNOME 40. If you have anything worthwhile to add to the font-size discussion, continue on the existing issue or open a new issue.

**Comment by francoism90** [comment]
@jnsh Sorry about that! So far it's looking good. :)

**Comment by jnsh** [comment]
Version [20210412](https://github.com/jnsh/arc-theme/releases/tag/20210412) with GNOME 40 support is out.

Closing.
