### ISSUE TITLE
[Need Help] Build process

### ISSUE THREAD

**Issue by SebTM** [jnsh/arc-theme#126]
Hey, thanks for the theme and your awesome work 👍🏻

I'm trying to update the Nixpkgs package for the latest release and the new (?) Meson build-workflow. Two problems still open, the theme is already building but I'm not sure if these points are important/as you would like:

- [x] While I think ninja is running I get 440-times this error for each element:
`
[1/440] Generating gtk2-light-arrow-left-prelight with a custom commandand
Unable to init server: Could not connect: Connection refused
Fontconfig error: Cannot load default config file
Exporting only object with id="arrow-left-prelight"; all other objects hidden.
Background RRGGBBAA: ffffff00
`

Tried to make font-config available during build and while researching about it I found an environment-variable (FONTCONFIG_PATH) which could help but while build-time the file the variable would point to wouldn't be availible.

- [ ] Lastly there was an install-command (https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/themes/arc/default.nix#L53) in post-install making docs and copying AUTHORS to share/docs. As I found out in postBuild as well as postInstall no Markdown-files as well as AUTHORS are present. Are they cleaned from Meson?

> drwx------ 2 nixbld nixbld      2 Apr 19 22:05 .cache
> drwxr-x--x 3 nixbld nixbld      3 Apr 19 22:05 .config
> -rw-r--r-- 1 nixbld nixbld     92 Apr 19 22:05 .gitignore
> -rw-r--r-- 1 nixbld nixbld    108 Apr 19 22:05 .hgignore
> -rw-r--r-- 1 nixbld nixbld  40498 Apr 19 22:06 .ninja_log
> -rw-r--r-- 1 nixbld nixbld 279569 Apr 19 22:05 build.ninja
> drwxr-xr-x 7 nixbld nixbld      7 Apr 19 22:05 common
> -rw-r--r-- 1 nixbld nixbld 184352 Apr 19 22:05 compile_commands.json
> drwxr-xr-x 2 nixbld nixbld     11 Apr 19 22:05 meson-info
> drwxr-xr-x 2 nixbld nixbld      4 Apr 19 22:06 meson-logs
> drwxr-xr-x 2 nixbld nixbld     10 Apr 19 22:05 meson-private

Please add the following information:

- Distribution and version. NixOS 20.09 (on nixpkgs-master/hm-master)
- Versions for the affected applications/desktops/tookits. X
- Installation method (package or compiled manually). Overlaying-Package before submit PR
- Arc-theme version. 20210412

**Comment by jnsh** [comment]
>  While I think ninja is running I get 440-times this error for each element:
>       `[1/440] Generating gtk2-light-arrow-left-prelight with a custom commandand Unable to init server: Could not connect: Connection refused Fontconfig error: Cannot load default config file Exporting only object with id="arrow-left-prelight"; all other objects hidden. Background RRGGBBAA: ffffff00`

The messages are coming from inkscape, and as long as the build doesn't fail, everything _should_ be ok.

>  Lastly there was an install-command (https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/themes/arc/default.nix#L53) in post-install making docs and copying AUTHORS to share/docs. As I found out in postBuild as well as postInstall no Markdown-files as well as AUTHORS are present. Are they cleaned from Meson?

The `AUTHORS` and the `*.md` files are still present in the source, but not in the meson build directory (where your `ls` output is from). Same goes for any other file that isn't generated in some way during the build process.

**Comment by SebTM** [comment]
Thank you for the fast response, I will try out something more for the doc thing - as I use the postInstall-hook from NixOS (https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/themes/arc/default.nix#L53) there is only the build result (from what I saw) available.

**Comment by SebTM** [comment]
Thanks for your support, got it fixed and will PR to nixpkgs 👍🏻
