### ISSUE TITLE
Firefox always starts with a space on the left side

### ISSUE THREAD

**Issue by francoism90** [jnsh/arc-theme#127]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts.
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details

Please add the following information:

- Arch Linux
- https://github.com/francoism90/pkgs/blob/master/arc-gtk-theme-git/PKGBUILD
- Firefox Developer Edition

Unless this is a non-visual issue, always add screenshots to help describe your problem.

![image](https://user-images.githubusercontent.com/5028905/115512252-11063600-a282-11eb-8183-490809985cf8.png)

When dragging (snapping) the window to a side, the issue disappears:

![image](https://user-images.githubusercontent.com/5028905/115512364-34c97c00-a282-11eb-85ec-5f5e22cd2b30.png)

It's not a big issue, maybe it has something to do with my Firefox installation, although the same issue happens on a new profile.

**Comment by jnsh** [comment]
This happens with any theme, so it's not in any way related to Arc.

The empty space is there intentionally when the window is not maximized/tiled, presumably to have some space for dragging the window if rest of the headerbar is filled with tabs. It has been present in Firefox for a long time.

Closing.

**Comment by francoism90** [comment]
@jnsh Didn't know this suppose to be feature! Sorry for reporting this issue. :+1:
