### ISSUE TITLE
Official Fedora Repository out of date

### ISSUE THREAD

**Issue by lolrepeatlol** [jnsh/arc-theme#131]
### Details

Please add the following information:

The official Fedora `arc-theme` repository is out of date. For Fedora 34, the latest release provided is...
![image](https://user-images.githubusercontent.com/17863082/117348890-c63b0f80-ae78-11eb-857b-e22fb4f56693.png)

That's pretty out of date. 

There's a newer release available for Fedora 35 (which isn't even a thing yet) but it's still not at the latest version either. 
![image](https://user-images.githubusercontent.com/17863082/117348978-dce16680-ae78-11eb-8ef3-4a14e47c2a6c.png)

Source: https://src.fedoraproject.org/rpms/arc-theme

I can add screenshots to show the result of the borked theme but I think it should be self-explanatory that the shell theme looks broken basically everywhere. Apps are fine though.

**Comment by lolrepeatlol** [comment]
> I'm not responsible for the distribution packages. Report this as a bug for the Fedora package, or contact the package maintainer (I'm not sure what's the appropriate way to report this with Fedora).

That's fine, I understand. I'm just not exactly sure how to contact them. 

For now, could you please remove the Fedora reference in the wiki to avoid confusion for other people?

**Comment by jnsh** [comment]
Looks like the Fedora package page has "Bug reports" button, which leads to bugzilla, which should be used to report issues I'd assume. Looks like there already is an open bug report for updating to the latest version: https://bugzilla.redhat.com/show_bug.cgi?id=1948655

As mentioned on the packages wiki page, there's also an unofficial COPR repository kindly provided by @mhdahmad, that seems to be now available for F34 as well. It also seems to have been updated to latest Arc-theme version, although it [appears](https://copr.fedorainfracloud.org/coprs/mhdahmad/workstation/build/2129974/) that its build has failed. Maybe @mhdahmad can provide more information on that situation?

> For now, could you please remove the Fedora reference in the wiki to avoid confusion for other people?

The purpose of the list is to provide names for the official packages, and not to keep in track which ones are up-to-date and working. Monitoring the status for all for all possible distribution packagess by myself would be a huge effort, and therefore doesn't really make sense to do that.

However, I could explain this more clearly on the package list, so I'll look at that at some point.
