### ISSUE TITLE
Icons not aligning correctly on dash GNOME 40

### ISSUE THREAD

**Issue by andri-reveli** [jnsh/arc-theme#133]
Icons are not vertically aligned correctly on gnome dash. The bottom part has no padding, while the top has padding.

Details:

- Distro: Fedora 34
- GNOME 40
-  Installation method: Fedora repo
- Package name: arc-theme-20201013-2.fc34.noarch.rpm

Arc Dark GNOME shell
![Arc Dark GNOME shell](https://user-images.githubusercontent.com/54241930/121216051-d5025100-c880-11eb-96c0-37dfef69a1dd.png)

Adwaita GNOME shell
![Adwaita GNOME shell](https://user-images.githubusercontent.com/54241930/121216058-d6337e00-c880-11eb-8041-d7e8a5e0db94.png)

**Comment by jnsh** [comment]
Version 20201013 does not support GNOME 40. Update to latest version, or build the theme from git repo, and get back if you have any remaining issues.

**Comment by jnsh** [comment]
Closing since there hasn't been any additional comments. I hope you got this sorted out.
