### ISSUE TITLE
Extensions app not themed on Gnome 40

### ISSUE THREAD

**Issue by Razer0123** [jnsh/arc-theme#134]
INFO 

- Archlinux, gnome 40.2
- Extension app is not themed, so i assume the theme is only partially working
- Installed via arc-gtk-theme
- 20210412

Unless this is a non-visual issue, always add screenshots to help describe your problem.

![Schermata del 2021-06-18 14-52-59](https://user-images.githubusercontent.com/1551395/122563812-f0214d80-d044-11eb-965e-b1bb2b72cafb.png)

**Comment by jnsh** [comment]
The extensions application is using GTK4, and since there's no Arc GTK4 theme available yet, it falls back to using the default Adwaita theme.

GTK4 support is tracked in #61, so I'm closing this as a duplicate issue.
