### ISSUE TITLE
Some coloring in the Gnome date menu and search bar is off

### ISSUE THREAD

**Issue by rdgh8** [jnsh/arc-theme#135]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts.
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details

Please add the following information:

- Distribution and version.
Pop!_OS 20.10
- Versions for the affected applications/desktops/tookits.
Gnome 3.38.3
- Installation method (package or compiled manually).
Package
- Arc-theme version.
20200819-2

Unless this is a non-visual issue, always add screenshots to help describe your problem.

https://user-images.githubusercontent.com/66289396/122656664-af036900-d12a-11eb-93e8-554f4593e36c.mp4

The events section of the system date tray is white with arc menu (dark) installed. Also, the search menu turns blue when characters are entered, although I'm not sure if that's intentional.

**Comment by jnsh** [comment]
Arc version 20200819 does not support GNOME 3.38, which added the events section to the calendar menu. Update to 20201013 or later.

The active search bar has always used the blue background color.

**Comment by rdgh8** [comment]
I just uninstalled and ran `sudo apt install arc-theme` again, the same version is being downloaded. Is building from source necessary for the latest version?

**Comment by jnsh** [comment]
If your distribution has an outdated package, which results in issues, I'm suggesting to request updating/fixing the package from the package maintainers.

If you can't find a working package for your distro, building from the source is likely the only option.

**Comment by rdgh8** [comment]
Thank you, closed.

**Comment by rdgh8** [comment]
Sorry, one more thing, is there any way I can manually change some setting/file to prevent the search bar from changing color?

**Comment by jnsh** [comment]
You can edit the source files, and rebuild the theme. More specifically look at `.search-entry` and things nested inside it in gnome-shell theme's `_common.scss`.
