### ISSUE TITLE
Text color in Arc Darker shell theme is so dark and unreadable. (Ubuntu 20.04)

### ISSUE THREAD

**Issue by anjuthanmj** [jnsh/arc-theme#144]
- Distribution and version - Ubuntu 20.04.2 LTS x86_64
- Affected Application - Notifications in notification panel (also pop up notifications)
- Installation method - package
- Arc-theme version - updated to latest. 

Note: I also faced issues in the calander text too but I have fixed it by changing css by following a thread in reddit. There is color issue in Ubuntu search box text too but I do not use it much so did not mention here. 
If I could install a version that is compatible for my OS version please let me know how to do it. Arc is my favorite theme and do not want to move away from it. Please help. 

![Screenshot from 2021-07-08 08-45-48](https://user-images.githubusercontent.com/26527505/124859316-50b10400-dfcd-11eb-8215-ea7e016feea3.png)

**Comment by jnsh** [comment]
>     * Arc-theme version - updated to latest.
_Latest version_ in this context should mean the latest version published here (i.e. 20210412), not latest package available from your distributions package manager. The official Ubuntu 20.04 package isn't even built from this repository, and this seems to be a known issue: https://bugs.launchpad.net/ubuntu/+source/arc-theme/+bug/1880018

> If I could install a version that is compatible for my OS version please let me know how to do it. Arc is my favorite theme and do not want to move away from it. Please help.

You can always build the theme yourself to be compatible with the GNOME version etc. of your distribution. See [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md) for instructions.

**Comment by anjuthanmj** [comment]
> he official Ubuntu 20.04 package isn't even built from this repository,

I did not know that. Thanks for pointing it out. I will try to build it manually. 


> You can always build the theme yourself to be compatible with the GNOME version etc. of your distribution. See [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md) for instructions.

If I use the gnome version, will the colors be corrected for that version, the building is for some package compatibility?

> his seems to be a known issue: https://bugs.launchpad.net/ubuntu/+source/arc-theme/+bug/1880018
I followed that solution for fixing the pop up banners but the system tray notification issue does not get fixed. I will try manual build.

**Comment by jnsh** [comment]
> > You can always build the theme yourself to be compatible with the GNOME version etc. of your distribution. See [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md) for instructions.
> 
> If I use the gnome version, will the colors be corrected for that version, the building is for some package compatibility?

If the theme is built for correct gnome-shell version, there shouldn't be any outstanding issues, such as unreadable text colors. 

With the rapid upstream gnome-shell development, usually every new version requires major theming changes. Therefore the gnome-shell version must be specified during build to match the shell version it will be used in. Using the incorrect shell theme version will most likely look broken to some degree.

**Comment by anjuthanmj** [comment]
I tried manual build from your installation guide, but I keep getting stuck at dependency errors and could not solve them. 
Which version of ubuntu is supports your repository so that I can install apt command to install it?

**Comment by anjuthanmj** [comment]
Successfully built and have set Arc as my theme. 

All elements that were messed up in my previous Arc themes are working fine. 

Thanks for the theme.
