### ISSUE TITLE
Artifacting only when arc-theme is used.

### ISSUE THREAD

**Issue by adatum** [jnsh/arc-theme#145]
Checkboxes and radio buttons are not shown correctly and are artifacting (looks like confetti) system-wide, but only for arc-theme. Click to expand the image below to compare the button representations between themes:

![arc_artifacts](https://user-images.githubusercontent.com/9773655/125664640-954f512a-e740-4053-bc52-c44857a5cd4c.png)

With arc-theme, certain programs have their entire windows similarly pink/artifacting, such as pidgin and linphone. 

Fedora 34 MATE
arc-theme-20210412-2.fc34.noarch installed from system package manager

Issue appeared on the first reboot after upgrading from arc-theme-20201013-2.fc34.noarch but not sure if it's related or just coincidence.

**Comment by jnsh** [comment]
I extracted the gtk3 theme from the arc-theme-20201013-2.fc34.noarch RPM package, and can reproduce the issue with it.
Many, if not all, of the pixmaps on the gtk3 theme are broken for some reason. However I can't reproduce this when I build the theme myself.

You should report this as a bug for the Fedora package. Unfortunately I can't tell what exactly has gone wrong with the package build, but the pixmaps are rendered during the build using inkscape, so probably something related to that.

You could try building the theme yourself, to check if the problem remains. If your self-built theme is broken as well, let me know if there are any errors/warnings during the build.

**Comment by adatum** [comment]
Thanks for investigating. Building from source shows no such problems. 

It appears the Fedora package has an issue, and others have reported as well: https://bugzilla.redhat.com/show_bug.cgi?id=1982160

**Comment by jnsh** [comment]
Thanks for linking the bug report. Looks like the PNG assets are broken with every theme that has them rendered during build, i.e. gtk2, gtk3 and xfce4 themes, so something must have gone wrong with that when building the package. If you have an account to the redhat bugzilla, this could be worth mentioning on the bug report, as it would probably help the package maintainer to diagnose the problem.

Thanks for reporting this anyway. I hope they got this sorted out soon.

**Comment by sisou** [comment]
As of yesterday morning [2021-07-28 01:24:12 UTC](https://bugzilla.redhat.com/show_bug.cgi?id=1982160#c20) a fixed `arc-theme` package is available for Fedora in the stable updates repo!

After updating (via Software or via `dnf`) you need to deactivate and reactivate the theme, either with the Tweak tool (just select another theme and back to the one you want) or by logging out and in again. :+1:
