### ISSUE TITLE
Gnome Wayland Titlebar Icons broken

### ISSUE THREAD

**Issue by stevewhitmore** [jnsh/arc-theme#146]
I noticed after updating to the latest kernel version that the titlebar icons appear to be broken. Instead of the normal icons they appear to be a rainbow of broken pixels.

I've toggled between themes (defaiult and otherwise), uninstalled this theme and reinstalled via dnf with restarts in-between but the issue remains.

I'm currently using Fedora 34 Workstation with Wayland. The kernel installed is 5.12.15-300.fc34.x86_64.

```
$ dnf info arc-theme
Last metadata expiration check: 0:26:17 ago on Fri 16 Jul 2021 01:35:30 PM CDT.
Installed Packages
Name         : arc-theme
Version      : 20210412
Release      : 2.fc34
Architecture : noarch
Size         : 16 M
Source       : arc-theme-20210412-2.fc34.src.rpm
Repository   : @System
From repo    : updates
Summary      : Flat theme with transparent elements
URL          : https://github.com/jnsh/arc-theme
License      : GPLv3+
Description  : 
             : Arc is a flat theme with transparent elements for GTK 3, GTK 2 and
             : Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments
             : like Gnome, Cinnamon, Budgie, Pantheon, XFCE, Mate, etc.

![Imgur](https://i.imgur.com/WJntl5Q.png)
![Imgur](https://i.imgur.com/7Vzdwta.png)


```

**Comment by jnsh** [comment]
This is a bug in the fedora package, that was already reported in https://github.com/jnsh/arc-theme/issues/145.

**Comment by stevewhitmore** [comment]
I searched for the same issue but missed it. Thanks!
