### ISSUE TITLE
Missing titlebar and broken minimize/maximize/close buttons

### ISSUE THREAD

**Issue by andycuccaro** [jnsh/arc-theme#147]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot: Done
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME): it doesn't (see [here](https://i.imgur.com/63xNPSi.png))
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts: it persists (even without saving session after restart)
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists: (it doesn't exist)

### Details

- Distribution and version: Fedora 34 Xfce spin
- Versions for the affected applications/desktops/tookits: Xfce 4.16 / xfwm 4.16.1
- Installation method (package or compiled manually): package
- Arc-theme version: 20210412

Screenshot:

![Image](https://i.imgur.com/7ZAiPLv.png)

**Comment by jnsh** [comment]
This is a problem in the Fedora package, see https://github.com/jnsh/arc-theme/issues/145.
