### ISSUE TITLE
icons corrupted in latest version

### ISSUE THREAD

**Issue by Deedss** [jnsh/arc-theme#148]
### Details

- Distribution and version: Fedora KDE 34
- Versions for the affected applications/desktops/tookits: GTK applications
- Installation method (package or compiled manually): Via package manager and official repo
- Arc-theme version: arc-theme-20210412-2.fc34.noarch

The icons used in the menu's for GTK applications are not working correctly in the latest update. Downgrading the package to the previous version of arc-theme-20201013-2.fc34.noarch fixes the issue. By checking the folder where the theme is installed, it shows all the icons to be corrupted. Images included are from the gnome-calculator with both arc-themes, the images with the corrupted icons is arc-theme-20210412-2.fc34.noarch and the correct one is with arc-theme-20201013-2.fc34.noarch. Also included is a screenshot of the images in the arc-theme installation folder. I've also noticed the corrupted icons in the xfwm4 folder. If you require any additional info, i'll try my best to add it. 

![arc-dark-1](https://user-images.githubusercontent.com/32330940/126755524-090a9d2f-30af-414c-bd30-cfbdad0ef97b.png)

![arc-dark-2](https://user-images.githubusercontent.com/32330940/126755525-f88b00af-2ea1-4aa6-9ea9-47e36315a064.png)

![arc-dark-3](https://user-images.githubusercontent.com/32330940/126755526-decceaaa-28b9-4a79-9564-c8adcfb42410.png)

![arc-dark-4](https://user-images.githubusercontent.com/32330940/126755529-bb347295-ce1f-4237-9e22-6e0238eed08a.png)

**Comment by jnsh** [comment]
See https://github.com/jnsh/arc-theme/issues/145
