### ISSUE TITLE
Any chance at reviving horst's other older themes?

### ISSUE THREAD

**Issue by Chaussettes99** [jnsh/arc-theme#151]
Howdy. Stumbled across this repo when trying to get horst's previous themes to work. Despite my efforts I don't really know what I'm doing and would like to ask if it's a possibility that horst's alternative themes like [Ceti-2](https://github.com/horst3180/ceti-2-theme) could be fixed up to work with modern Gnome/Budgie.

**Comment by jnsh** [comment]
Hello. Certainly they _could_ be updated and fixed, but I myself definitely won't be up for the task, as I still have plenty of things to do for Arc.

Also, based on what I've learned from working with Arc, I'd say it's probably easier to start a new theme from scratch, than getting a theme that's been unmaintained for more than 5 years into shape.
