### ISSUE TITLE
Text contrast

### ISSUE THREAD

**Issue by lnicola** [jnsh/arc-theme#153]
Hello!

Would it be possible to increase the text contrast It's partly a matter of taste, of course, but text in Adwaita looks much better to me. Look at the labels below:

![image](https://user-images.githubusercontent.com/308347/129204551-0838536c-e460-4cc1-9519-ecbefbfce97f.png)

![image](https://user-images.githubusercontent.com/308347/129204567-1cf1b27f-eee3-4bdd-8c79-82502cde8af7.png)

This was prompted by an inadvertent change in Firefox. Below, the left rendering is a bug, while the right is how it's supposed to look like with Arc. I think the left version looks much better.

![image](https://user-images.githubusercontent.com/308347/129204711-e0df36e0-2309-4df0-b52d-1114dc1264bf.png)

Here is Firefox with Adwaita:

![image](https://user-images.githubusercontent.com/308347/129204930-feb66003-260e-4036-bd72-22f53df32aec.png)

**Comment by jnsh** [comment]
This has been discussed ad nauseam, and won't be changed. See https://github.com/jnsh/arc-theme/wiki/Common-problems#text-against-light-background-is-too-lightlow-contrast

Changing the `$text_color` and `$fg_color` variables for SASS based themes works, but the text won't be changed for the rest of the themes. The above link has a suggested `sed` command that can be used to change the text color in all source files, and therefore all themes.

**Comment by lnicola** [comment]
Ah, sorry. I checked the open issues, but not the closed ones.

I can understand your stance on not making significant changes to the theme. I still think it's a desirable change, but it's fair enough if you don't want that.
