### ISSUE TITLE
XFCE: Panel icons enlarge while they are clicked to activate

### ISSUE THREAD

**Issue by zhangkaizhao** [jnsh/arc-theme#162]
The panel icons enlarge while they are clicked to activate on XFCE.

![simplescreenrecorder-2021-11-13_12 59 26](https://user-images.githubusercontent.com/7512811/141606681-1349a9a5-cf98-4c57-8d01-56ca52e90f11.gif)

- OS: Arch Linux x86_64
- XFCE: 4.16
- Installation method: `sudo pacman -S arc-gtk-theme
- Arc-theme version: 20211018

**Comment by jnsh** [comment]
For future reference, this only seems to happen if using larger fixed icon size, from xfce4-panel appearance preferences.

I'll push a fix for this shortly.
Thank you for the report :)
