### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by atar-axis** [jnsh/arc-theme#163]
I am trying to install the latest (as of today) version of this git repository on Ubuntu 21.10.
I tried to install the gtk3 and gtk4 version, but sadly none worked :(

While running `meson setup -Dthemes=gnome-shell,gtk3 --prefix=$HOME/.local build/` I got the error:
`Run-time dependency gtk+-3.0 found: NO (tried pkgconfig and cmake)`

While running `meson setup -Dthemes=gnome-shell,gtk4--prefix=$HOME/.local build/` I got the error:
`Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)`

**Comment by jnsh** [comment]
Either install the package with pkgconfig files for gtk, or define the gtk versions manually with e.g. `gtk3_version` build option.

See the [versioned themes](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#versioned-themes) section in INSTALL.md

**Comment by atar-axis** [comment]
looks like you need `libgtk-3-dev` on ubuntu :)

**Comment by atar-axis** [comment]
On Ubuntu you need to install `libgtk-3-dev` or `libgtk-4-dev`. Maybe worth mentioning in the README?
Thanks for your work!

**Comment by jnsh** [comment]
Already mentioned in the INSTALL.md section I linked above :)

Closing.

**Comment by atar-axis** [comment]
Oh man, you are right... Absolutely my fault. I am sorry!
