### ISSUE TITLE
Mate: System Monitor in panel has white borders

### ISSUE THREAD

**Issue by bjo81** [jnsh/arc-theme#164]
![Bildschirmfoto zu 2021-12-02 22-40-49](https://user-images.githubusercontent.com/1674578/144509306-0c6941a7-fdd2-4cba-9e67-36f106642b1a.png)

The boxes from the system monitor has white borders, but I think they should be black like e.g. in the materia theme. The issues exists with the latest release and also with a current git build.

OS: Arch Linux
DE: Mate 1.26.0
Theme: Arc

**Comment by jnsh** [comment]
Thank you for the report.

I can agree the border doesn't look appealing, and it is now hidden with https://github.com/jnsh/arc-theme/commit/dee21542b15bdd14d8ca1046fe6f764aae335af8
