### ISSUE TITLE
This theme creates a top border on firefox now

### ISSUE THREAD

**Issue by NoXPhasma** [jnsh/arc-theme#165]
### Details

Please add the following information:

- Distribution and version: Arch Linux
- Versions for the affected applications/desktops/toolkits: Cinnamon 5.0.7
- Installation method (package or compiled manually): [AUR](https://aur.archlinux.org/packages/arc-gtk-theme-git/)
- Arc-theme version: arc-gtk-theme-git-20211018.r24.gb92056cc-1

In Firefox arc theme now creates a big border on top of firefox, if the title bar is hidden. It is either in theme style when windowed or black when in maximized. This does not happen with other themes like Adapta. This is a rather new issue and didn't happened before.

### Steps to reproduce:
- open firefox and edit toolbars. 
- at the bottom left uncheck the titlebar checkbox

### Screenshots
Arc:
![grafik](https://user-images.githubusercontent.com/7719590/145363872-d3487a31-9f7a-47e0-8e18-f807e17a12b5.png)
![grafik](https://user-images.githubusercontent.com/7719590/145364025-ac82b20f-31b7-4f4c-a6fb-787ac58b2837.png)
Adapta:
![grafik](https://user-images.githubusercontent.com/7719590/145364185-0715a516-9796-41f5-afea-921686308f36.png)
![grafik](https://user-images.githubusercontent.com/7719590/145364299-c555beb5-8752-4baf-bec1-b535d19037c6.png)

**Comment by jnsh** [comment]
Thank you for the report.
I must have missed this with the recent metacity updates. I'll figure out a fix soon
