### ISSUE TITLE
Can't build on Ubuntu 20.04.3 clean install

### ISSUE THREAD

**Issue by cvetan** [jnsh/arc-theme#166]
When I try to build theme on clean Ubuntu 20.04 install I get the error, that I didn't get up until now, and I have build these theme fair number of times:
I run this command: 

```
meson setup --prefix=/usr -Dthemes=gnome-shell,gtk2,gtk3,metacity -Dtransparency=false build/
```

And here is the output:
```
The Meson build system
Version: 0.53.2
Source dir: /home/cvetan/Downloads/arc-theme
Build dir: /home/cvetan/Downloads/arc-theme/build
Build type: native build
Project name: arc-theme
Project version: 20211018
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Program inkscape found: YES (/usr/bin/inkscape)
Program meson/install-file.py found: YES (/home/cvetan/Downloads/arc-theme/meson/install-file.py)
Configuring index.theme.light using configuration
Configuring index.theme.darker using configuration
Configuring index.theme.dark using configuration
Configuring index.theme.lighter using configuration
Program gnome-shell found: YES (/usr/bin/gnome-shell)
Configuring gnome-shell-light.scss using configuration

common/gnome-shell/meson.build:122:8: ERROR: add_install_script args must be strings

A full log can be found at /home/cvetan/Downloads/arc-theme/build/meson-logs/meson-log.txt
```

Did something changed in the build process lately, and maybe instructions were not updated?

**Comment by cvetan** [comment]
I checkout older commit from before these meson changes and the build passed.

**Comment by jnsh** [comment]
Sorry I forgot that the recently added install script must be passed as as string to keep support for meson <0.55.0.

I'll push a fix in a minute.

**Comment by cvetan** [comment]
Yes, it works now. Thanks. :beer:

**Comment by eli-schwartz** [comment]
This is a meson bug, it should have warned you with a FeatureNew check that you were using something which required meson 0.55.

Sorry. This should be fixed in the next version of meson.
