### ISSUE TITLE
Arc-Dark / Arc-Darker: colours don't match screenshots

### ISSUE THREAD

**Issue by WhyNotHugo** [jnsh/arc-theme#172]
**System info**
- ArchLinux
- gtk3 3.24.31
- Installed via repository packages
- theme version 20220102

The colours I'm seeing being used don't match those in the screenshots -- I'm seeing some more "neutral" greys.

The top bar on the file manager is #2F343F, but it's #333843 in screenshots:

![image](https://user-images.githubusercontent.com/730811/151641501-9e8aad9f-9929-4aea-a5a4-614a788627b5.png)

For Firefox's equivalent top bar, the colour is #2F343F too:

![image](https://user-images.githubusercontent.com/730811/151641693-e953c1d6-cada-4c4b-9a26-f2f1420a2112.png)

**Comment by jnsh** [comment]
The client-side-decorated GTK3 headerbars are 3% transparent, so the light background in the screenshot causes them to appear slightly lighter than if there were no transparency.

It would probably be a good idea to use a background that makes the transparency more apparent for the screenshots.

**Comment by WhyNotHugo** [comment]
Ah, so that's it. I agree that the screenshot should somehow reflect that, but I can't think of an obvious way to do so.

Any idea why I'm not seeing them as transparent at all?

**Comment by jnsh** [comment]
> Ah, so that's it. I agree that the screenshot should somehow reflect that, but I can't think of an obvious way to do so.

I think that should be somehow possible with the background image on the "Full preview" (same background is being used with the current screenshots, but aligned in a way that the transparency isn't apparent). I'll update the screenshots at some point. Thank you for the heads up :)

> Any idea why I'm not seeing them as transparent at all?

The most obvious reason could be using the non-transparent Arc-solid variants, but I'm assuming that isn't the case :)

The headerbar transparency is unfortunately not working with some GTK applications. At least all GTK4 applications and GTK 3 applications that are using libhandy have non-transparent backgrounds, and that probably can't be fixed. Firefox doesn't have a "regular" GTK headerbar, and therefore isn't transparent. I'm not sure what file manager you're using on the first screenshot, so I can't tell what could be going on with it...

**Comment by WhyNotHugo** [comment]
It's nemo on the first screenshot. I don't think any application has shown this transparency, but I'm not sure if my compositor actually supports that either.

**Comment by jnsh** [comment]
I have updated the preview screenshots so, that the transparency is more apparent. I think that's all to be done here, so I'm closing this.

**Comment by WhyNotHugo** [comment]
Thanks for the help here.

I have to admit I liked the colours in the screenshots a bit better than the "real" one, but I'm also very aware that changing them is not an option since that would lead to a huge amount of people complaining that **they** don't have the same preference I do.
