### ISSUE TITLE
Latest changes have no window controls on some windows

### ISSUE THREAD

**Issue by cvetan** [jnsh/arc-theme#175]
I have checked out and installed latest changes on Ubuntu 20.04.4 and I discoveded some issues. 

For instance Sublime Text window has no window controls until you hover over them. This wasn't the case earlier, so I think some of the latest changes introduces this issue.

You can see screenshots bellow.

![Screenshot from 2022-02-27 14-59-37](https://user-images.githubusercontent.com/5733322/155885464-d1582c06-b331-4115-b5c8-bb10ab5e5ac1.png)
![Screenshot from 2022-02-27 14-59-41](https://user-images.githubusercontent.com/5733322/155885469-c83d457d-d945-4f00-b1df-80fb9da18e39.png)

**Comment by jnsh** [comment]
Did you confirm that you don't have similar issues with default themes?

I didn't see arc-theme getting update from official package sources for Ubuntu 20.04, so this should not result from changes, unless you've installed the theme from some other sources. Either way, could you try building the latest version of the theme, to see if that solves your issue?

If that didn't help, please let me know what desktop environment or window manager you're using. And whether you're experiencing this same issue with other applications besides sublime text? Also, you're saying you've discovered "some issues" and the one with sublime text is only a single example, so can you detail what other issues you're experiencing.

**Comment by cvetan** [comment]
Do you mean deafult theme of Sublime Text, or default theme of window manager? I did build theme from this repository and with latest commit, as per instructions for install. I've used no other sources, beside this since you forker theme. :D

I did check with default adwaita theme, and it didn't have issue. You can see down screenshot with arc theme build from some of the older commits, and with default adwaita theme. 

And I am using gnome on ubuntu 20.04 .
arc theme - older commits build
![Screenshot from 2022-02-27 15-53-08](https://user-images.githubusercontent.com/5733322/155887415-22a1de7a-a69f-40ab-9b4a-20fe75587aaa.png)

adwaita theme
![Screenshot from 2022-02-27 15-53-37](https://user-images.githubusercontent.com/5733322/155887427-7e1aa5a5-44b5-4ddb-ba15-dfc85eb1f520.png)

**Comment by jnsh** [comment]
Sorry, I think I misunderstood your first post, and thought you meant that an Ubuntu update broke the theme, If the theme was built yourself, and this started happening after some recent changes, then this is clearly something resulting from the theme itself :)

I'm unfamiliar with Sublime Text, but the screenshots look like it's not using decorations from GNOME's window manager, but does its own decorations based on the GTK theme. I need to investigate this further, but https://github.com/jnsh/arc-theme/commit/45b46b529984dad14d0ecc9999a9aec9752b36bd might have resulted in this.

Can you tell which version of sublime text you're using, so I can use the same version for testing?

**Comment by cvetan** [comment]
Sublime text 4126 with Agila theme

**Comment by jnsh** [comment]
Apparently this happens with some sublime text themes, although the default theme seemed unaffected.

Arc-theme draws its custom titlebar buttons with a background-image, and makes the standard button icons transparent. Looks like this results in somewhat odd behavior with how some of the sublime text themes are done, and forcibly hiding the icon with 45b46b529984dad14d0ecc9999a9aec9752b36bd made it even worse.
