### ISSUE TITLE
Ugly marks in sliders of the Xfce PulseAudio panel plugin

### ISSUE THREAD

**Issue by radioactiveman** [jnsh/arc-theme#176]
### Details

Since the update of Arc-gtk-theme to 20220223, the sliders in the Xfce PulseAudio panel plugin contain ugly marks.
This is not the case in gtk3-widget-factory. I am not sure yet what the panel plugin does differently to the slider.

- Distribution and version: Arch Linux
- Versions for the affected applications/desktops/toolkits: Xfce 4.16, GTK 3.24.33, xfce4-pulseaudio-plugin 0.4.3
- Installation method (package or compiled manually): package
- Arc-theme version: 20220223

Before (20220102):
![01_Before](https://user-images.githubusercontent.com/1301412/156895362-d82c6359-74d3-451f-a515-780ac1887b63.png)

After (20220223):
![02_After](https://user-images.githubusercontent.com/1301412/156895366-2d76a701-fe7e-4640-a4e9-2a41ac5e5c7a.png)

**Comment by jnsh** [comment]
Fixed in https://github.com/jnsh/arc-theme/commit/f4e1593262927d68b5ac98968b1e3ec876fdf9b1. Indeed the pulseaudio-plugin menu does something unusual with the switches.
Thanks for the report.
