### ISSUE TITLE
ERROR: Problem encountered: Could not determine Cinnamon version

### ISSUE THREAD

**Issue by 0pLuS0** [jnsh/arc-theme#177]
### Details

Please add the following information:

- Distribution and version - Slackware 15.0
- Openbox 3.6.1
- Installation method - compiled from source
- Arc-theme version - 20220223

The source is saying; Could not determine Cinnamon version

How can I disable it looking for Cinnamon and build this?

I thought in the archives you have for download, you also provide the theme compiled already? I thought arc-theme-20220223.tar.xz is the bult theme, because it says source for the tar and zip archives to download.

Here's the output;

meson setup --prefix=$HOME/.local -Dvariants=light build/                   
The Meson build system
Version: 0.59.4
Source dir: /home/foo/Downloads/arc-theme-20220223
Build dir: /home/foo/Downloads/arc-theme-20220223/build
Build type: native build
Project name: arc-theme
Project version: 20220223
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Program inkscape found: NO
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program meson/render-assets.py found: YES (/usr/bin/python3 /home/foo/Downloads/arc-theme-20220223/meson/render-assets.py)
Configuring index.theme.light using configuration
Program cinnamon found: NO

common/cinnamon/meson.build:12:2: ERROR: Problem encountered: Could not determine Cinnamon version

**Comment by 0pLuS0** [comment]
It looks like more issuse because I only run Openbox, it's also looking for gnome, and the others, so I'm hacking those all away, so I can just build only the gtk themes.

**Comment by jnsh** [comment]
This behavior is explained in [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#versioned-themes).

**Comment by 0pLuS0** [comment]
I only want the GTK 2,3,4 themes, can you please provide these for download without needing to compile them?

THANKS

**Comment by 0pLuS0** [comment]
I see the build options in the INSTALL.md, I just don't understand which one I use to make;

cinnamon, gnome-shell, metacity-1, plank, unity and xfwm4 ```false```?

THANKS

**Comment by 0pLuS0** [comment]
Ok, I just ran it like this;

>meson setup --prefix=$HOME/.local -Dthemes=gtk2,gtk3,gtk4 -Dvariants=light build/ 
The Meson build system
Version: 0.59.4
Source dir: /home/foo/Downloads/arc-theme-20220223/arc-theme-20220223
Build dir: /home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/build
Build type: native build
Project name: arc-theme
Project version: 20220223
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Program inkscape found: NO
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program meson/render-assets.py found: YES (/usr/bin/python3 /home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/render-assets.py)
Configuring index.theme.light using configuration
Program /home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py found: YES (/home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py)
Program /home/rog/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py found: YES (/home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py)
Configuring gtk-dark.scss using configuration
Configuring gtk-light.scss using configuration
Configuring gtk-light.gresource.xml with command
Program /home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py found: YES (/home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py)
Configuring gtk-light.css with command
Configuring gtk-dark.css with command
Configuring gtk-dark.scss using configuration
Configuring gtk-light.scss using configuration
Configuring gtk-light.gresource.xml with command
Program /home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py found: YES (/home/foo/Downloads/arc-theme-20220223/arc-theme-20220223/meson/install-file.py)
Configuring gtk-light.css with command
Configuring gtk-dark.css with command
Build targets in project: 6


But build/common/gtk2 is empty and the gtk3 and gtk4 directories didn't properly build either, they don't have the correct files in them.

**Comment by 0pLuS0** [comment]
Here's the contents of /build/common for the GTK themes.

[build.tar.gz](https://github.com/jnsh/arc-theme/files/8229004/build.tar.gz)

**Comment by jnsh** [comment]
With all due respect, please read the install instructions thoroughly. You haven't built anything by running `meson setup`, only configured the build directory. This is all instructed in INSTALL.md. Additionally you can have a look at Meson build system documentation, if you aren't familiar with using it.

**Comment by 0pLuS0** [comment]
I apologize, I've been a bit jump on this, my bad... :(

I wasn't thinking there... :(

THANKS

**Comment by jnsh** [comment]
No worries, I hope you figured it out.
I'm happy to help if there's something specific you don't understand in the build documentation, and improve it if possible. Or if you encounter any issues not explained there.

Unfortunately providing universal pre-build theme package isn't feasable at the moment, so building it is the only option if your distribution doesn't provide packages, and I'm trying to make it as painless as possible. Although, you could probably extract the GTK themes from pre-built packages for other distribution without any issues.

**Comment by 0pLuS0** [comment]
I've just been jumpy and really pushing it, because I just installed Slackware 15.0 after all the years on 14.2 waiting for a new release, and now all the work to get a fresh install of 15.0 up and running.

So I was rushing through this, sorry to have posted this, if I would of just slowed down and READ!

Your time was greatly apprecaited, keep up the great work, I hope this ARC project will live for many years, I've been using ARC since it came out.

THANKS
