### ISSUE TITLE
Implement $accent-color and other variables in libadwaita

### ISSUE THREAD

**Issue by apandada1** [jnsh/arc-theme#179]
### Details

- Distribution and version: Manjaro XFCE (fully updated as of 3rd April 2022).
- Versions for the affected applications/desktops/toolkits: [blanket](https://github.com/rafaelmardojai/blanket) (GTK4/libadwaita)
- Installation method (package or compiled manually): master branch compiled manually from [github](https://github.com/rafaelmardojai/blanket) - commit https://github.com/rafaelmardojai/blanket/commit/cb28ca358110425aee207613a32d524faea41f57
- Arc-theme version: Git commit https://github.com/jnsh/arc-theme/commit/f4e1593262927d68b5ac98968b1e3ec876fdf9b1

Blanket uses the variable `accent-colors` in its [css file](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_colors.scss#L6), and arc theme does not have it. As a result, icons of the active sounds are shown in white (almost invisible) in Arc theme, while they are nicely visible in libadwaita.

### default libadwaita theme

![libadwaita](https://user-images.githubusercontent.com/3063132/161421442-fdc3c2aa-f587-4133-b2ad-690d35824cda.jpg)

### Arc theme
![arctheme](https://user-images.githubusercontent.com/3063132/161421462-a2af79ff-bae4-47c7-9714-33a2cf150842.jpg)

accent-color is a [property](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_colors.scss#L9) of libadwaita, which matches the accent color choosen in the gnome system settings.

I don't know much css, but a possible solution would be to globally define the variable `accent-color == the-blue-color-used-in-arc-theme` in the css files of arc theme.

**Comment by jnsh** [comment]
Thanks for the report. I noticed the new color definitions when working on libadwaita, but forgot to add them. I'll sort this out soon :)

> accent-color is a [property](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_colors.scss#L9) of libadwaita, which matches the accent color choosen in the gnome system settings.
> 

For reference, the libadwaita specific color properties that can be used by applications are defined in [_defaults.scss](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_defaults.scss), _colors.scss just defines the SASS color variables. There are some additional properties in [_compat-colors.scss](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_compat-colors.scss), that I think are part of the default GTK4 theme as well.

**Comment by jnsh** [comment]
This is fixed with https://github.com/jnsh/arc-theme/commit/4411abeb3d2dbd7b3c8b5a42f259d4d29c3fd993

**Comment by apandada1** [comment]
Great!!! I can confirm that the issue is fixed.

**Comment by yochananmarqos** [comment]
Unfortunately this will not work in GNOME 42. Libadwaita applications use the global system theme and only "legacy" applications will use the selected custom theme.

**Comment by jnsh** [comment]
@yochananmarqos That's not what this issue was about, so this is not the right place for that discussion.

However, GNOME version doesn't matter with libadwaita applications, and setting the GTK_THEME environment variable globally does work.

**Comment by yochananmarqos** [comment]
@jnsh Sorry about the noise, then. The global variable does work, turns out I had a typo.
