### ISSUE TITLE
Theme do not apply correct if selected dark mode in Gnome 42

### ISSUE THREAD

**Issue by phush0** [jnsh/arc-theme#180]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts.
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details
![Screenshot from 2022-04-07 10-30-34](https://user-images.githubusercontent.com/5719362/162144734-57c0f1b8-e278-48c0-b019-61485a3ad761.png)

Please add the following information:
![Screenshot from 2022-04-07 10-30-48](https://user-images.githubusercontent.com/5719362/162144753-a1e6a3d2-90ce-49f0-9def-d11923e09eb3.png)

- Distribution and version. - Arch 5.17.1 
- Versions for the affected applications/desktops/toolkits. Gnome 42
- Installation method (package or compiled manually). AUR 
- Arc-theme version. master

Unless this is a non-visual issue, always add screenshots to help describe your problem.

**Comment by jnsh** [comment]
This seems to happen with Arc-Dark variant, where there is no separate dark theme available. Apparently with the new dark style preference, Adwaita-Dark is used instead of falling back to using the "regular" Arc-Dark, which was the old behavior when applications requested dark theme.

Fix will be pushed shortly.

**Comment by FreddieChopin** [comment]
BTW why some applications - like the control panel in the background on the screenshot - don't use Arc theme now? Is this something that is missing in Arc (gtk4?) or maybe there was some change in GNOME and some windows are not-theme-able now? This also happens for "Extensions" application, calculator, but works fine for a lot of others (like gedit, gnome tweaks, ...).

**Comment by jnsh** [comment]
@FreddieChopin See e.g. this post: https://bbs.archlinux.org/viewtopic.php?pid=2030402#p2030402

**Comment by jhanschoo** [comment]
Hi, is it possible to release a new build incorporating this fix?

**Comment by jnsh** [comment]
@jhanschoo I should have some time to get back at Arc-theme again next week, and I'll look at fixing some pending things, and then will likely roll out a new release.

**Comment by jhanschoo** [comment]
Thanks!

**Comment by evenfrost** [comment]
@jnsh I'm not familiar with the package release procedure for Ubuntu, but is it possible to release `20221218-1` for the current Ubuntu distribution (22.10)?

I [see that this release](https://launchpad.net/ubuntu/+source/arc-theme) exists only for 23.04, which is not released yet.

**Comment by jnsh** [comment]
@evenfrost I'm not responsible for distribution packages. I don't think ubuntu backports packages for the theme, but you could try opening a bug report for them.

I think newer .deb packages from other ubuntu versions or debian based distributions could work though, except for gnome-shell and cinnamon themes could have issues if the versions aren't matching with the ones shipped on your distribution.

If nothing else works, you can always build the theme yourself.
