### ISSUE TITLE
Ibus popup menu is transparent

### ISSUE THREAD

**Issue by kevinhwang91** [jnsh/arc-theme#181]
### Before submitting

- Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- Make sure the issue persists between restarts.
- For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details

Please add the following information:

- ArchLinux gnome42
- gnome42 ibus
- compiled manually
- master-branch

Arc-Dark-solid:
![image](https://user-images.githubusercontent.com/17562139/162561171-617c3c6a-3112-406a-bb21-6669dab8ba9e.png)

gnome-classic:
![image](https://user-images.githubusercontent.com/17562139/162561186-dfcdff60-b01e-447f-9f0a-2f8ff8a562e2.png)

**Comment by jnsh** [comment]
Sorry I had missed this during the update.

This should be fixed with https://github.com/jnsh/arc-theme/commit/7039f6f229b679ca9d713ba1d780cd769e344cb1

**Comment by kevinhwang91** [comment]
Thanks a lot, fixed now.
