### ISSUE TITLE
Ugly marks in sliders of the Xfce Power Manager panel plugin

### ISSUE THREAD

**Issue by radioactiveman** [jnsh/arc-theme#183]
### Details

The same issue as in #176 affects also the Xfce Power Manager panel plugin.
Maybe it is better to use a more general CSS rule than making it application specific?

- Distribution and version: Arch Linux
- Versions for the affected applications/desktops/toolkits: Xfce 4.16, GTK 3.24.33, xfce4-power-manager 4.16
- Installation method (package or compiled manually): package
- Arc-theme version: 20220405

### Screenshot
![Screenshot](https://user-images.githubusercontent.com/1301412/164976497-9083c29b-ae2e-46e3-ac71-15dfcf4653b0.png)

**Comment by jnsh** [comment]
Thanks for the heads up! The earlier xfce4-pulseaudio-plugin fix is now applied to all xfce4 panel popups.
