### ISSUE TITLE
Shell 42 - Compress menu does not expand

### ISSUE THREAD

**Issue by TJonCooper** [jnsh/arc-theme#184]
Distribution: Ubuntu 22.04
Affected application: Nautilus 42.0
Arc-Theme compiled manually (pulled ~5m ago from master) for gtk3,gtk4,gnome-shell
Variant: arc-dark

Steps to reproduce:

R-click -> Compress -> attempt to change the type of compression (e.g. from .zip to .7x)

The menu that pops up to offer the options does not expand as expected and therefore is largely unreadable:

![Screenshot-20220429103111-568x301](https://user-images.githubusercontent.com/15924377/165902092-fb438b7f-4654-43f1-b06b-1e3ab34fe2bd.png)

Arc-dark is set for both the shell and legacy applications.

**Comment by jnsh** [comment]
I can't reproduce the issue, although for me the popup opens to down and not left and I can't seem to change that.

Either way, this doesn't seem like something obviously related to the theme.
Did you make sure that the issue doesn't happen with the default Adwaita theme as well?
