### ISSUE TITLE
Shell 42 - Notification window is squared and contents are not aligned

### ISSUE THREAD

**Issue by TJonCooper** [jnsh/arc-theme#185]
Distribution: Ubuntu 22.04
Arc-Theme compiled manually (pulled ~5m ago from master) for gtk3,gtk4,gnome-shell
Variant: arc-dark

Steps to reproduce:

Initiate any notification e.g.:

notify-send "Test Title" "Blah blah blah blah"

The notification window is almost completely squared (whereas natively in Shell 40/41/42 it has rounded corners) and the notification icons are not aligned with the text.

![Screenshot-20220429103850-607x97](https://user-images.githubusercontent.com/15924377/165903411-4d682cab-2d52-4e51-9a82-864f7598fa97.png)

The squared window issue is something seen throughout most of arc-theme on Shell 42 at the moment.

**Comment by jnsh** [comment]
The notification icon is aligned better with https://github.com/jnsh/arc-theme/commit/b13cff7b1a24bfb37ddccfb3f2ac868c0d835efd.
However, how it actually aligns with the title depends on things like the used font, and font scaling.
