### ISSUE TITLE
in GTK 4.2 arc theme do not work in some application (gnome-calendar, gnome-calculator)

### ISSUE THREAD

**Issue by PowaBanga** [jnsh/arc-theme#187]
Hi everybody, i post a message here because arc theme do not work on 42.0 version of gtk. I do not know what to say more... Just that i hope that can be fix! :)
I tried too with this command : 
`GTK_THEME=arc-ark:dark gnome-calculator `
But it's adwaita theme who is loaded...
- Distribution and version.
- Archlinux (latest)
- Versions for the affected applications/desktops/toolkits.
-  42.0
- Installation method (package or compiled manually).
- using AUR repository
- Arc-theme version.
-  20220405-1

![](https://i.imgur.com/toIPUKX.png)

**Comment by jnsh** [comment]
> I tried too with this command : `GTK_THEME=arc-ark:dark gnome-calculator ` But it's adwaita theme who is loaded...
- `arc-ark` is a typo
- I'm not certain but it maybe be case sensitive as well, i.e. `GTK_THEME=Arc-Dark:dark`
- also the `:dark` variant isn't working for Arc-Dark with the 20220405 release due to [#180](https://github.com/jnsh/arc-theme/issues/180), so just use `GTK_THEME=Arc-Dark`

**Comment by PowaBanga** [comment]
you was right !
`GTK_THEME=Arc gnome-calculator` and `GTK_THEME=Arc gnome-calculator`
fix temporary the arc theme for this applications, so now, i have to find how to make it permanent.

**Comment by jnsh** [comment]
Since you're using Arch, take a look at Arch Wiki page about [environment variables](https://wiki.archlinux.org/title/Environment_variables).

This has nothing to do with the theme any more, and since you got your problem solved, I'm closing this.

**Comment by Razer0123** [comment]
This seems to be happening also with Gnome-extensions

**Comment by Razer0123** [comment]
Seem to have fixed adding that to .profile

What about root apps? is it possible to fix it for them too?

**Comment by jnsh** [comment]
@Razer0123 This has nothing to do with Arc-theme any more.

The solution is explained above. If you don't know how to apply it, seek help from the support channels for your distribution.
