### ISSUE TITLE
How Can I get this on KDE

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [jnsh/arc-theme#19]
Is there a way to get this theme on KDE based distribution ?

**Comment by arun54321** [comment]
GTK themes work on gtk apps on even on KDE too.

**Comment by Ashutosh-Kukreti** [comment]
So it will be applicable to gtk apps only and not KDE apps?
I guess I've to wait then till someone port it to KDE store.

**Comment by arun54321** [comment]
> So it will be applicable to gtk apps only and not KDE apps?
> I guess I've to wait then till someone port it to KDE store.

https://github.com/PapirusDevelopmentTeam/arc-kde

**Comment by jnsh** [comment]
I'm aware of the [arc-kde](https://github.com/PapirusDevelopmentTeam/arc-kde) theme that @arun54321 mentioned, as it was mentioned on the README of the original Arc-theme project. However I'm not in any way affiliated with it, and I have no idea of how well it works, or whether it's still maintained. Other than that, your search results should be as good as mine.

The Arc GTK themes can naturally be used in GTK applications under KDE. If that's unclear to you, please refer to support channels of your preferred distribution.
