### ISSUE TITLE
Chrome apps have no border or shadow on Unity

### ISSUE THREAD

**Issue by pumpkinlink** [jnsh/arc-theme#191]
### Details

- Ubuntu 22.04 with Unity 7
- Affected application: Chrome 101.0.4951.64 (Official Build) (64-bit)
.
- Installation method: official Ubuntu APT repo.
- Arc-theme version: 20220405
 
Arc-Dark:
![169344747-eeac7b8d-7c19-4a09-b8b2-2728a43f2f9d](https://user-images.githubusercontent.com/11864620/169538706-ac6bc485-241e-4566-a221-3b64f9c1afdb.png)

Yaru-Dark:
![169344877-35124f0f-7c82-4465-8b4c-2293e6d50d54](https://user-images.githubusercontent.com/11864620/169540075-b0ccecdb-96e1-4dd6-84b2-d2a506bab3ab.png)

Ambiance:
![169345074-5ce4d81d-7ee8-4825-94bc-e13bf114b668](https://user-images.githubusercontent.com/11864620/169539749-44a8078b-cfc9-42ab-b9ed-786a20805076.png)

**Comment by jnsh** [comment]
Can you try rebuilding the theme from current master? I'm hoping https://github.com/jnsh/arc-theme/commit/2570e8ebe1eeaf90d131c07a235ac06e69776db5 would fix this, but don't have any chrome apps set up to test this.

**Comment by pumpkinlink** [comment]
It works! thank you!
I tested setting meson to only build the gtk3 theme first and it already fixed my specific use case
![image](https://user-images.githubusercontent.com/11864620/169434419-68dc69e9-02de-4808-b354-64979bf8d7ed.png)

**Comment by jnsh** [comment]
Happy to hear that worked. Thank you for testing it!

Closing.
