### ISSUE TITLE
Variant request 

### ISSUE THREAD

**Issue by JAAnon** [jnsh/arc-theme#192]
Hi, I am running an Arch-based distro with a light orange/yellowish color scheme. I don't have a DE, just using Openbox and pcmanfm. I would love to use Arc or Arc Darker in combination with Papirus icons, and it would be great to have an orangish variant of the theme that would be more consistent with the distro color scheme than the default blue accent and highlighted entries. Would it be possible for you to create it? Thanks and keep up the great work.

**Comment by jnsh** [comment]
Sorry but I don't provide additional color variants.

You can use `sed` on the theme source to change each hex color value to your liking before building. This can be done quite handily within a custom PKGBUILD for Arch. You may find tips from older issues for variant requests, where this has been discussed
