### ISSUE TITLE
Artifacts on titlebars of tiled windows in Cinnamon 5.4

### ISSUE THREAD

**Issue by sudorook** [jnsh/arc-theme#194]
Distribution: Arch
DE: Cinnamon 5.4.2
Installation: Compiled
Version: current HEAD

**Issue:** When focusing/switching tiled windows, the titlebar disappears partially. It gets offset downward, leaving a black region in its place. GIF below.

![Peek 2022-06-26 00-36](https://user-images.githubusercontent.com/6200846/175800960-ab4e830b-0576-4e21-8f55-51ded075135c.gif)

I haven't seen this behavior with the default Adwaita or other third-party themes (Plata, Adapta, Matcha, and Qogir). I'm stumped about why it's only an Arc issue. I'd guess something to do with the metacity files... but I don't know.

Background: Cinnamon recently released version 5.4, which mainly features a rebase of its window manager (muffin) on a more recent version of mutter. This has caused a bunch of visual oddities, but there above one is the only substantial problem I've encountered.

**Comment by jnsh** [comment]
Looks very similar to https://github.com/jnsh/arc-theme/issues/188, but this happens with any application?

I looked at muffin changelog, but didn't immediately notice anything that seemed related.
I'm quite busy for few weeks, but I'll try to have a proper look at this at some point.

> Background: Cinnamon recently released version 5.4, which mainly features a rebase of its window manager (muffin) on a more recent version of mutter. This has caused a bunch of visual oddities, but there above one is the only substantial problem I've encountered.

If you can detail the other (Arc specific) visual oddities that appeared with the 5.4 update, no matter how small, that could be helpful.

**Comment by smurphos** [comment]
The main change is that all titlebars are themed by the GTK theme now, the metacity theme is unused.

**Comment by jnsh** [comment]
@smurphos Thanks for the info! I was wondering whether that could be the case, but didn't notice anything in the changelog.

There's probably a common cause in the GTK3 theme for this issue and #188, and also there could a dconf setting similar to [this](https://github.com/jnsh/arc-theme/issues/188#issuecomment-1124491573) that works as a temporary solution until there's a proper fix.

**Comment by sudorook** [comment]
> Looks very similar to https://github.com/jnsh/arc-theme/issues/188, but this happens with any application?

Yes, or at least all the ones I've tested (e.g. Firefox, Calibre, kitty, nemo, etc.)

> There's probably a common cause in the GTK3 theme for this issue and https://github.com/jnsh/arc-theme/issues/188, and also there could a dconf setting similar to https://github.com/jnsh/arc-theme/issues/188#issuecomment-1124491573 that works as a temporary solution until there's a proper fix.

That works. I set `/org/cinnamon/muffin/draggable-border-width` to the `25`.

> If you can detail the other (Arc specific) visual oddities that appeared with the 5.4 update, no matter how small, that could be helpful.

I will should I find any. All of the others I've noticed are theme-agnostic.

As far as this issue is concerned, it seems it is the same as #188, though with muffin and not mutter. I'll refrain from closing as no fix has been identified, only a workaround.

**Comment by jnsh** [comment]
Fixed with https://github.com/jnsh/arc-theme/commit/651747bd1b47bd7b2ac8de718da3782bfa4cc210

**Comment by robsdedude** [comment]
Hi @jnsh thanks for the timely fix. Please consider creating a release with this patch included. It's frankly quite annoying and considering the last release was in April 2022, I've been wondering if there's an ETA for the next release.

Thanks for maintaining this beautiful theme either way!

**Comment by jnsh** [comment]
@robsdedude Next release is planned immediately after I am able to update the theme for GNOME 43.
