### ISSUE TITLE
Issue with Arc-Lighter and Firefox

### ISSUE THREAD

**Issue by tupo2** [jnsh/arc-theme#195]
- Distribution and version: Ubuntu 22.04
- Versions for the affected applications/desktops/toolkits: GTK 3.24.33
- Installation method (package or compiled manually): Package
- Arc-theme version: 20220405

I encounter an issue with Arc-Lighter and Firefox, the windows decorations are incorrect:
![arc-lighter](https://user-images.githubusercontent.com/42449735/178268636-078ab06c-f0af-488d-ae31-6526f9fc1716.png)

On the other hand, no problem with Arc, Arc-Dark and Arc-Darker:
![arc](https://user-images.githubusercontent.com/42449735/178268903-83799f54-97f0-4b18-ab71-bfacaf41f784.png)

**Comment by jnsh** [comment]
I can't reproduce this on my system, and didn't immediately see anything wrong with the Ubuntu package.

-Does every other application work without issues using Arc-Lighter?
-Are there any warnings/errors when using Arc-Lighter, if you start firefox from command line, that aren't there when using the other variants?

**Comment by tupo2** [comment]
> -Does every other application work without issues using Arc-Lighter?
 
No, Ubuntu Software has the same issue, which is also a Snap application like Firefox (but with the other variants, no problem).

> -Are there any warnings/errors when using Arc-Lighter, if you start firefox from command line, that aren't there when using the other variants?

This displays: **Failed to load module "canberra-gtk-module"**.
Same for other variants.
I did: `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` but it didn't help.

**Comment by tupo2** [comment]
I found 2 workaround:
Unclear why changing directory name of the theme works:
```
sudo mv /usr/share/themes/Arc /usr/share/themes/Arc-Light
sudo mv /usr/share/themes/Arc-Lighter /usr/share/themes/Arc
or
sudo mv /usr/share/themes/Arc-Lighter /usr/share/themes/Arc-Dark
or
sudo mv /usr/share/themes/Arc-Lighter /usr/share/themes/Arc-Darker
```

2nd workaround:
```
sudo snap remove firefox
sudo add-apt-repository ppa:mozillateam/ppa
sudo apt install firefox=102.0.1+build1-0ubuntu0.22.04.1~mt1
```
