### ISSUE TITLE
Fully disable shadows on borders ( feature request )

### ISSUE THREAD

**Issue by cuzrawr** [jnsh/arc-theme#197]
Hello, very like this theme for years, its part of my linux desktops everywhere, but im always feel pain with shadows.
There no easy way to disable it without writing custom gtk.css, and put everywhere something like this:

````
cat .config/gtk-3.0/gtk.css 
.window-frame {
box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1), 0 8px 8px 0 rgba(0, 0, 0, 0.2);
  /*  margin: 0;  */
}
.window-frame:backdrop {
box-shadow: none;
}

.window-frame:backdrop,
.window-frame,
.window-frame.tiled,
.window-frame.popup{
box-shadow: none;
}

.window-frame.tooltip.csd,
.window-frame.popup.csd,
.window-frame.popup {
border-radius:0px;
box-shadow: none;
}

* {
box-shadow: none;
}
.label {
    text-shadow:none;
/*    color:black;       Font color. */
}

/* Chromium-specific case */
.entry.chromium {
        box-shadow: none;
        border-radius:0px;
}

/* Chromium-specific case */
entry.chromium {
    box-shadow: none;
    border-radius:0px;
}
````

Its very weird thing and seems broke some borders. Im sure` css is fun`, but please add option to build this theme without shadows at window borders.  

System without shadows looks more clean and solid.

Thank you.

**Comment by jnsh** [comment]
Sorry, but I won't implement an option to disable shadows.

There has been numerous request to add build options to implement various visual tweaks that someone would prefer. However it makes no sense to add options for every small tweak someone might want. The theme will follow the original design, and any visual changes belong to separate forks.
