### ISSUE TITLE
GNOME shell popup menu item highlights are not shown while using keyboard navigation

### ISSUE THREAD

**Issue by gvaleika** [jnsh/arc-theme#200]
### Details

Please add the following information:

- Distribution and version.
Archlinux, current.

- Versions for the affected applications/desktops/toolkits.
GNOME version 42.4, Xorg.

- Installation method (package or compiled manually).
Archlinux package

- Arc-theme version.
Arc

GNOME shell popup menu item highlights are not shown while using keyboard navigation(keys Up, Down). Menu items are highlighted when mouse is over them correctly.

Using Adwaita - shell popup menu navigation (Power, Lock, Settings, Network etc.) items are highlighted while using keyboard navigation.

**Comment by jnsh** [comment]
This should be fixed already with https://github.com/jnsh/arc-theme/commit/9125d2f6b5057df34ce03efeec384b43df536f23, but the fix is not in the latest release.
You could test whether you still have this issue if you install `arc-gtk-theme-git` from AUR.

**Comment by gvaleika** [comment]
Can confirm it works.
