### ISSUE TITLE
Why does it need gnome-shell

### ISSUE THREAD

**Issue by madhur** [jnsh/arc-theme#203]
I am trying to install this theme on Linux mint with i3 as window manager. The build process fails with missing `gnome-shell` dependency. Why does it need gnome-shell for theme installation.

We can use theme for gtk apps under i3 manager?

**Comment by jnsh** [comment]
Please read the [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#versioned-themes) thoroughly. You can avoid this by either disabling gnome-shell theme building, or by defining the version for it manually.
