### ISSUE TITLE
Display goes black when switching to Arc themes

### ISSUE THREAD

**Issue by bradrn** [jnsh/arc-theme#204]
When I switch from a non-Arc theme to an Arc theme in the Xfce dialog entry ‘Settings→Appearance→Style’, the whole display goes black. What happens after this varies: sometimes a blinking cursor appears at the top-left of the screen and I can switch to another tty, sometimes no cursor appears and I can’t switch to any other tty, and once my login screen (LightDM) appeared after a few seconds. In any case, after I reboot the computer, I find that the theme has applied successfully; it seems to be specifically an issue with switching to an Arc theme. Curiously enough, switching between Arc-* themes doesn’t seem to trigger this issue — it seems to occur only when switching to any Arc theme from Adwaita, Adwaita-dark or High Contrast (those being the only three other themes I have installed). Likewise, switching back to those themes works perfectly.

I am using Xfce 4.16 on EndeavourOS ‘Artemis Nova’ 22.9 (so in essence Arch), with `arc-gtk-theme 20220405-1` and `arc-solid-gtk-theme 20220405-1` installed using `pacman`. The issue also occurs with EndeavourOS’s `arc-gtk-theme-eos`, though I’m not sure precisely how that’s different to the others or how EndeavourOS installed that package.

**Comment by jnsh** [comment]
Your desktop environment shouldn't crash even if if there was some issue with the theme. I'd suggest requesting help from your operating system's support channels to debug this. Also, it might be good idea to test if this happens with other themes as well.

If you can figure out what about the theme causes the crash, I'd still love to fix it if possible. However without any error messages I can't even guess what could be causing this.

**Comment by bradrn** [comment]
Sounds like reasonable advice, thanks!

**Comment by bradrn** [comment]
Hmm, this seems to have gone away completely. Not sure what I did exactly, but it doesn’t seem like a problem with Arc at all. Sorry for cluttering up the issues with this!
