### ISSUE TITLE
Problems with tiled windows.

### ISSUE THREAD

**Issue by Initu-Castilhos** [jnsh/arc-theme#206]
When tiled the blurred window is on top of the problem as shown in the image below.
![Captura de tela de 2023-02-12 19-38-53](https://user-images.githubusercontent.com/59381215/218341649-1e4e2c22-5927-4b2a-99b8-ce9a20632484.png)
![Captura de tela de 2023-02-12 19-38-59](https://user-images.githubusercontent.com/59381215/218341659-55ac5f53-f51b-499b-a43c-c65dcb511fe4.png
- Linux Mint 21.1
-  Cinnamon 5.6.7

**Comment by jnsh** [comment]
This should be fixed in the latest release version 20221218

**Comment by jnsh** [comment]
Since there's been no response, I'm assuming this is fixed for the issue author as well.. closing
