### ISSUE TITLE
New To This

### ISSUE THREAD

**Issue by gerguter** [jnsh/arc-theme#21]
Hello, I am new to Linux. I am trying to build and install your theme but can't seem to get it to work. I have installed the dependencies but the make install command gives me an error code.

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
Detected GTK3 3.24.14
Building GTK3 theme 3.24
checking for gnome-shell... yes
Detected GNOME Shell 3.34.4
Building GNOME Shell theme 3.34
checking for cinnamon... no
        
configure: WARNING: Could not find cinnamon from $PATH.
configure: error: Could not determine Cinnamon version. Install Cinnamon, or use the --with-cinnamon=<version> option. Alternatively you can choose to not build the Cinnamon theme with --disable-cinnamon option.
configure: WARNING: cache variable ac_cv_prog_CINNAMON_FOUND contains a newline

make: *** No rule to make target 'install'.  Stop.

Not sure what to make of it. I have googled and I am stumped. Thanks for your time.

**Comment by gerguter** [comment]
I actually figured it out. Thank you for your time in keeping this theme going!

**Comment by brneor** [comment]
Can you share how did you solve this issue? :)

**Comment by jnsh** [comment]
The solution is explained in the error message:

>`configure: error: Could not determine Cinnamon version. Install Cinnamon, or use the --with-cinnamon= option. Alternatively you can choose to not build the Cinnamon theme with --disable-cinnamon option.`

See [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#build-options) for further details about the build options.
