### ISSUE TITLE
GNOME Shell 44 regressions

### ISSUE THREAD

**Issue by omentic** [jnsh/arc-theme#212]
I'd imagine you've already seen this, but there are some new issues with the quick menu in GNOME 44:

![image](https://user-images.githubusercontent.com/35242550/237045071-2735a2f7-be18-4deb-986c-966f523d5a3c.png)

**Comment by jnsh** [comment]
Yes.. I will sort this out along with the other issues once I got the time to update the shell theme for 44.

**Comment by jnsh** [comment]
Using this issue to track all GNOME Shell 44 regressions now.

One more thing is the top panel border, as mentioned in #211
![Screenshot from 2023-05-07 09-15-18](https://user-images.githubusercontent.com/1524089/236689686-2b3f7265-4764-43f8-9301-922fff1249c8.png)

Please add a comment if anyone notices something else that hasn't been mentioned yet.

**Comment by omentic** [comment]
Build for Arch: [arc-gtk-theme.zip](https://github.com/jnsh/arc-theme/files/12386641/arc-gtk-theme.zip)

**Comment by omentic** [comment]
I'll reopen this if I notice any regressions but so far everything seems good. Thanks a bunch.
