### ISSUE TITLE
Top right corner extension drop down menus look bad on GNOME Shell 45

### ISSUE THREAD

**Issue by xuanruiqi** [jnsh/arc-theme#216]
- Distribution: Arch Linux
- GNOME Shell version 45.0
- Arc theme: git head, compiled manually

As said in the title, some extension menus look bad:

![Screenshot from 2023-10-13 02-42-34](https://github.com/jnsh/arc-theme/assets/14145609/53f6f4c5-d412-451d-8675-6fe63b8f1707)

More specifically, the padding to the left is much smaller than the padding to the right, causing the menu look "cut" from the left.

I've tested with the default Adwaita theme, which does not have this issue.

**Comment by xuanruiqi** [comment]
apparently, the same happens with the applications menu

**Comment by jnsh** [comment]
These will be fixed once I have time to sync up the gnome-shell theme for GNOME 45

**Comment by jnsh** [comment]
Apologies for the delay. I've updated the gnome-shell theme for 45 finally. Please let me know if you still notice any oddities.
