### ISSUE TITLE
Theme not applying in some apps

### ISSUE THREAD

**Issue by AndreiTS** [jnsh/arc-theme#217]
Ubuntu 23.10
Compiled Manually
arc-theme 20221218

User defined options:
 - gnome_shell_gresource: true
 - gnome_shell_version  : 45
  - themes                   : gnome-shell,gtk3,gtk4
  - transparency         : true
  - variants                  : dark

![image](https://github.com/jnsh/arc-theme/assets/13489837/9fe5834e-d1ef-4a10-b79e-fe581ea22c1e)

**Comment by jnsh** [comment]
See e.g. https://github.com/jnsh/arc-theme/issues/189

I should add this to the [common problems](https://github.com/jnsh/arc-theme/wiki/Common-problems) page as well
