### ISSUE TITLE
Alignment Issues With Nautilus

### ISSUE THREAD

**Issue by zeyadtamimi** [jnsh/arc-theme#220]
Hey folks,

I am running Arch Linux with Hyprland as my compositor.

I just installed the theme from the official arch repositories and applied it using:

```
gsettings set org.gnome.desktop.interface gtk-theme Arc-Dark
export GTK_THEME=Arc-Dark
```

The theme does appear to "apply" correctly but there are two issues:

1. The navigation section and the main folder view top bars are somehow misaligned
2. There is a black outline around some of the buttons 

![2023-12-28_14-10](https://github.com/jnsh/arc-theme/assets/14227029/d96fee86-97e7-4da1-adef-869f82a8220e)

For contrast, the default theme looks like:

![2023-12-28_14-16](https://github.com/jnsh/arc-theme/assets/14227029/d7eb3cdb-cd75-4179-82b3-d33db78450fa)

I tried looking at the frequent issues page but could not find anything related to this. Any help would be greatly appreciated.

**Comment by jnsh** [comment]
With applications that use libadwaita such as Nautilus, anything from their own built in stylesheet can't be overridden with the theme. Mismatches with the builtin stylesheet, and custom theme result in thise issues. Unfortunately this can't be fixed

**Comment by zeyadtamimi** [comment]
Ah, that's rather unfortunate.

Regardless, thank you so much for your quick reply!
