### ISSUE TITLE
What about the icons?

### ISSUE THREAD

**Issue by itaranto** [jnsh/arc-theme#221]
Aside from the original [GTK theme](https://github.com/horst3180/arc-theme), @horst3180 made also an [icon theme](https://github.com/horst3180/arc-icon-theme).

It would be nice if the icons could be revised / maintained here as well.

I know this is probably a big effort, and I'm not gonna complain if you don't accept this request.

It's just sad the icons didn't receive the same attention as the GTK theme.

**Comment by jnsh** [comment]
As far as I can tell, the arc icon theme was barely started and only contains few base icons, so a lot would have to be created from scratch. Really don't have time or interest for the task tbh.
