### ISSUE TITLE
[SOLVED] Gnome Shell quick settings looks bad

### ISSUE THREAD

**Issue by medicamin** [jnsh/arc-theme#222]
- Distribution: Arch linux, updated to 01 March 2024
- arc-gtk-theme: 20221218-1
- Installation method: pacman
- Gnome: 45.4

This is how gnome-shell appears with the arc theme:
![Screenshot from 2024-03-01 21-09-11](https://github.com/jnsh/arc-theme/assets/17678405/38d1c8c3-426e-4a15-9ed5-ffe2736e61bb)

**Comment by jnsh** [comment]
The latest release, which is the one available from Arch repos only supports gnome-shell versions up to 43. The quick settings menu was updated in gnome 44, which messed up its appearance. The theme is updated in git fixing the quick settings, so you could use arc-gtk-theme-git from AUR, but be aware of this build issue: https://github.com/jnsh/arc-theme/issues/214#issuecomment-1685090829

**Comment by medicamin** [comment]
Thank you. So I mark this issue solved
