### ISSUE TITLE
Arc Valyrian fork

### ISSUE THREAD

**Issue by bungadrum** [jnsh/arc-theme#224]
Could you add a forked version off Valyrian theme that is Arc based as well? The theme doesn't support GTK 4 nor does it have the traditional WM header bar with buttons at least not on XFCE where I tested it. It is a very unique fork off Arc, but it doesn't work on any Libadwaita apps. I use a lot of Flatpaks and this theme doesn't work on it at all. The theme hasn't been active almost a year could you add a fork of it with GTK 4 /Libadwaita support to keep up with todays modern themes soon GTK 5 will be upon this awesome theme will be forgoten by then. The maintainer hasn't been active lately. 

The theme is available both on Github and on Pling:

https://www.gnome-look.org/p/1955721

https://github.com/rtlewis1/GTK/tree/VALYRIAN

![val1](https://github.com/user-attachments/assets/2787cffd-3729-4397-9472-1ac5439b45db)
![val2](https://github.com/user-attachments/assets/6a10a6af-56fa-464f-941e-76cd4bdf973c)

**Comment by jnsh** [comment]
Definitely don't have time to maintain a whole another theme, even if that was feasible and I was interested. Sorry.
