### ISSUE TITLE
Missing elements like separator lines

### ISSUE THREAD

**Issue by AngryPhantom** [jnsh/arc-theme#228]
Another issue that strikes the eye is some missing things like separator lines, for example:

Arch Linux, XFCE: panel clipman plugin

This is how it should look (Adwaita):
![a](https://github.com/user-attachments/assets/f5ba3064-c994-4dac-bd17-5e89fdb22fe0)

And this is how it looks in Arc:
![c](https://github.com/user-attachments/assets/9128eb46-7b1a-4376-ba1b-aa0cda737b6c)

The same with the XFCE panel's dark theme.

I guess the theme should be updated in order to keep up with GTK and stuff like that.

Please don't abandon your work since it's the best out there, IMHO (I've tried almost every one of them and it's the best for the eyes and extremely elegant).

TIA

**Comment by jnsh** [comment]
Separator lines were never part of the design. I believe adding them has been requested before, but I'm going to stick with the design choices of the original author.

**Comment by AngryPhantom** [comment]
Got it! No problem then, just wasn't aware of this. Closing the issue.
