### ISSUE TITLE
Dash to Panel custom Show Application icon support

### ISSUE THREAD

**Issue by ariflukito** [jnsh/arc-theme#23]
Hi, I'm using Dash to Panel extension and the extension allows you to customise the "Show Application" icon. 

As you can see below, there's a black background if I use a custom icon.
![image](https://user-images.githubusercontent.com/5508660/77396155-47f7e700-6df7-11ea-9208-7ddf02f31f7f.png)

and here's the clicked state.
![image](https://user-images.githubusercontent.com/5508660/77396587-2814f300-6df8-11ea-9192-4746c23f5aaf.png)

Would you be able to make those look nicer. Thank you in advance.

**Comment by jnsh** [comment]
I had a quick look at dash-to-panel, code and I don't think it's possible to change the themeing specifically for the customized-show-apps-icon case.

Even if it was possible, I think changing the default show-apps icon styling for this case would only make the theme more inconsistent, and I can't really think of a better alternative styling that would work with all custom icons.

The dash-to-panel extension seems to mess up the icon background border radius for the clicked state though, but you should bug the extension developers about that.

If you customize the shop apps icon, I'd recommend using some purely white icon with no background (e.g. white Arch linux logo with no background), as it should work best with Arc theme.

If you want to tweak the theme for your personal use, you can try editing the `.show-apps .overview-icon`, and/or `.show-apps .show-apps-icon` style on the gnome-shell theme SASS.

**Comment by ariflukito** [comment]
Thank you jnsh. I'll try bring it up to dash-to-panel developers and see what they say.
