### ISSUE TITLE
Thank you jnsh!

### ISSUE THREAD

**Issue by martijnboers** [jnsh/arc-theme#25]
### Thank you
I just wanted to say it, seeing how after the previous fork was archived I went on to a deep dive into the world of GTK themes but didn't find anything close that's as good as the Arc theme.

I don't know how long you plan on maintaining this and if this will become the next official-non-official repository but your efforts are greatly appreciated

Please close this at any time as it is not a bug/feature request

**Comment by jnsh** [comment]
Thank you for the kind words. I'm happy if anyone finds my work useful.

I'm committed to maintaining the theme for now. I've already been working on it for more than a year, and don't see any reason for not continuing in the foreseeable future.
