### ISSUE TITLE
gtk-3.0 sass/css building to srcdir

### ISSUE THREAD

**Issue by fgblomqvist** [jnsh/arc-theme#29]
This is a bit of a crapshoot, but I've been stuck trying to figure out why my build script is failing for quite some time now and I think I've finally reached some sort of conclusion.

How to replicate (assuming theme is checked out):
```
mkdir newbuild
cd newbuild
../configure --srcdir=..
make
```
The error I get:
```
cp "gtk-dark.css" "dark/gtk-main.css"
cp: cannot stat 'gtk-dark.css': No such file or directory
```
The file is present here: `common/gtk-3.0/3.24/gtk-dark.css` but the cp command is looking here: `newbuild/common/gtk-3.0/3.24/gtk-dark.css`. I'm not sure what the correct location is, but it feels like sass should put the files in the newbuild one instead of the root one. Either way, they're seemingly out of sync atm.

**Comment by jnsh** [comment]
Is there a reason for not following the build instructions?

I'm not sure if using `--srcdir=` parameter in this manner should be expected to work with autoconf/automake projects. Either way, I'm probably not going to fix this without a good reason.

The build system is a bit of a mess atm, and very hard to develop further for me. I'm planning on rewriting it eventually, but until that happens, following the build instructions in [INSTALL.md ](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md)should work.

**Comment by fgblomqvist** [comment]
Yeah I mean building it normally works fine but I was trying to build an rpm using the specfile for the existing package (https://src.fedoraproject.org/rpms/arc-theme/blob/master/f/arc-theme.spec). Idk if it's common practice to do it that way (using `--srcdir`), but oh well. I'll just modify it to work in a different way instead.
