### ISSUE TITLE
[gnome-3.36] menu tweaks needed?

### ISSUE THREAD

**Issue by jnqnfe** [jnsh/arc-theme#32]
The menu at the top right of the screen (what do we call this?) could possibly do with tweaking under Gnome 3.36

arc:
![arc](https://user-images.githubusercontent.com/33935229/79081668-793d4600-7d17-11ea-8fe0-c3485b18da74.png)

adwaita:
![adwaita](https://user-images.githubusercontent.com/33935229/79081670-7e01fa00-7d17-11ea-8932-c6b6e2d953f3.png)

**Comment by jnsh** [comment]
Is this with current `master` branch, and built with `--with-gnome-shell=3.36`? These should be fixed already.

**Comment by jnqnfe** [comment]
Oh, damn, sorry, I'm forgetting to say that I'm coming from Debian. The debian package version is currently 20190917+git20200328-1.

I did start off reporting one issue in the Debian BTS but was asked to file upstream.

If you've already addressed in things and Debian just needs to update then I apologise for wasting your time and I can go back to Debian to request they simply update the package.

**Comment by jnsh** [comment]
Odd, these should be fixed with a git snapshot from 20200328.

If it's not too much trouble, could you try if the issues persist if you build the theme yourself? If there are no issues with the built theme, there's probably something off with the debian package.

**Comment by jnqnfe** [comment]
Erm, I'll maybe take a look a doing that tomorrow, it's pretty late and I think I'm too tired to face that at the minute. :)

**Comment by jnsh** [comment]
No worries. If building the theme is too much work, I'd suggest reporting this as a bug on the debian package anyway.

I can't really think how these should still be present in correctly built theme from git master. The sub-menu border was fixed in commit https://github.com/jnsh/arc-theme/commit/4f9e124683069b5255d964ebe52a8c3e6711f4d8, and separators in commit https://github.com/jnsh/arc-theme/commit/125e04d56d2c6321469d46981ca70ceb3f74e69d, so I'm pretty sure this has to be an packaging issue.

@fossfreedom If you see this, would you mind taking a look?

**Comment by fossfreedom** [comment]
Debian transitioned to 3.36  in the last few days. So the package needs the shell parameter tweaked from 3.34 to 3.36. 

That will be tossed into unstable later today.

**Comment by jnsh** [comment]
@fossfreedom That explains this. Thank you.

@jnqnfe This and #33 should get fixed in the forthcoming debian package update.

**Comment by jnqnfe** [comment]
With the package updated now and having rebooted, things are much improved.

However I'd argue that this menu could still do with some tweaking
 - The big gap between 'log out' and 'suspend' is a little odd, with the divider now being invisible.
 - The amount of space on the left seems a little excessive.
 - The menu entries *are* usable with the touchscreen on my laptop, but are a little on the small side (even with Hi-DPI scaling at 200%)...

![menu](https://user-images.githubusercontent.com/33935229/79280221-b6384280-7ea7-11ea-8270-66d21339b882.png)

**Comment by jnsh** [comment]
> The big gap between 'log out' and 'suspend' is a little odd, with the divider now being invisible.

That's the standard gnome-shell menu separator. It has always been like that with Arc theme. I do agree that it has always looked a bit odd, and I've been thinking about adjusting it at some point. However, this is not a GNOME 3.36 specific issue.

> The amount of space on the left seems a little excessive.

There was a regression in this with gnome 3.36, that is now fixed in `master` with https://github.com/jnsh/arc-theme/commit/06e8c1584893e689b0e8e8f35e1227296cdd78ad.


> The menu entries are usable with the touchscreen on my laptop, but are a little on the small side (even with Hi-DPI scaling at 200%)...

Again, this has not changed in the GNOME 3.36 cycle. I'll keep your concern in mind, but Arc theme has always had a more compact design, and I'm not planning on changing that.

**Comment by jnqnfe** [comment]
> > The big gap between 'log out' and 'suspend' is a little odd, with the divider now being invisible.
> 
> That's the standard gnome-shell menu separator. It has always been like that with Arc theme. I do agree that it has always looked a bit odd, and I've been thinking about adjusting it at some point. However, this is not a GNOME 3.36 specific issue.

Maybe it existed before, but I do not recall seeing it anywhere. I've just updated another system and saw it nowhere beforehand. I'll take your word that it did exist before, but the problem is that it's much more prominent now under 3.36 with their redesign of the power-off/logout entries.

> > The menu entries are usable with the touchscreen on my laptop, but are a little on the small side (even with Hi-DPI scaling at 200%)...
> 
> Again, this has not changed in the GNOME 3.36 cycle. I'll keep your concern in mind, but Arc theme has always had a more compact design, and I'm not planning on changing that.

There may be no difference to the margins, but it's become a bigger problem under 3.36. The main entries I use with the touchscreen are wifi, settings, and power-off/logout. The latter ones of course used to be large round buttons, perfectly suited to touch input. The wifi entry was the only area I used where I felt the margins were not perfectly suited to touch, presenting a target area a little smaller than I felt it should be. Now under 3.36 this affects all of these common entries.

Taking a couple of minutes to experiment on a screenshot in gimp, I think a bump to ~130% entry height would give a more comfortable size.

> There's some major refactoring planned for the gnome-shell theme based on changes to the default shell theme in 3.36 though. This should eventually allow editing the margins, paddings etc. of the theme to your liking with relative ease.

**Comment by jnsh** [comment]
> Maybe it existed before, but I do not recall seeing it anywhere. I've just updated another system and saw it nowhere beforehand.

You should see the separator e.g. in all application menus, and between the volume/brightness sliders and the menu items below. As I said, I'm planning on improving the separators, but it's not GNOME related issue, but requires adjusting the separators consistently within every theme.

> Taking a couple of minutes to experiment on a screenshot in gimp, I think a bump to ~130% entry height would give a more comfortable size.

I'm not going to break the original design by adjusting menu item sizes. It's unfortunate if this doesn't work best for you, but there are also users that would prefer even more compact design. There's nothing stopping you from adjusting the theme for your own preference locally, or in separate fork.

**Comment by jnsh** [comment]
@jnqnfe Something I didn't think of earlier, is that the font-size has an effect on the overall menu item size as well. Currently the font-size on the gnome-shell theme is rather small, so you may be able to improve your experience by increasing the size.

You can do that by increasing the 'Scaling Factor' via `gnome-tweaks` (or `/org/gnome/desktop/interface/text-scaling-factor` dconf key), or by editing the theme SASS files before compiling.

My plan is to increase the default font size to be a bit more comfortable as well, hopefully in the near future.
