### ISSUE TITLE
[gnome-3.36] calendar tweaks needed

### ISSUE THREAD

**Issue by jnqnfe** [jnsh/arc-theme#33]
Tweaks to the calendar needed under Gnome 3.36. The combination of text and background colours make some of the text barely readable. (Especially considering it's shown much smaller on screen than in the below cropped screenshot).

![cal](https://user-images.githubusercontent.com/33935229/79081727-eb158f80-7d17-11ea-87a9-6bd69c3e0b5c.png)

**Comment by jnsh** [comment]
The same as in https://github.com/jnsh/arc-theme/issues/32, the calendar background should already be fixed with `master`. There are still some padding/margin fixes on the works for the calendar popup though.

**Comment by jnqnfe** [comment]
confirm fixed
