### ISSUE TITLE
[gnome-3.36] stray vertical line of transparent pixels in eog

### ISSUE THREAD

**Issue by jnqnfe** [jnsh/arc-theme#34]
In Gnome 3.36, I see a stray vertical line of transparent pixels to the right hand side of images viewed in eog.

I do not see this in adwaita.

I have a HI-DPI screen with 200% scaling.

**Comment by jnqnfe** [comment]
update: in fact I notice now that there's also a stray horizontal line at the bottom of pictures also.

**Comment by jnqnfe** [comment]
further update: oh, double checking that the horizontal line also does not appear under adwaita, in fact I am now seeing both lines showing up under adwaita, so maybe it's a gnome issue...

**Comment by jnsh** [comment]
Could you post a screenshot? I don't notice any vertical lines in eog myself.

**Comment by jnqnfe** [comment]
Looking further I believe it's a Gnome issue not an arc-theme issue. I've reported it and dicussed it further here: https://gitlab.gnome.org/GNOME/eog/-/issues/122

Example:
![Screenshot from 2020-04-13 00-14-56](https://user-images.githubusercontent.com/33935229/79082209-e8b53480-7d1b-11ea-8a87-a98f28192340.png)
