### ISSUE TITLE
Notifications color changed after updating xfce4-notifyd

### ISSUE THREAD

**Issue by malnvenshorn** [jnsh/arc-theme#35]
The color of the notifications changed after updating `xfce4-notifyd` from version `0.4.4` to `0.6.0`. I'm using `arc-darker`.

With `0.6.0`:

![1](https://user-images.githubusercontent.com/13801805/79252380-cc330c80-7e81-11ea-8eb2-ab59e360165a.png)

With `0.4.4`:

![2](https://user-images.githubusercontent.com/13801805/79252378-cb9a7600-7e81-11ea-97fe-f60119b36ddb.png)

I'd like to get the dark notifications back when using  `arc-darker`.

Btw. it's awesome that you still maintain this theme!

**Comment by imShara** [comment]
@malnvenshorn move notification-related code from `arc-dark` to `ark-darker`

**Comment by jnsh** [comment]
Thanks for the report. I'll look into this.

> I'd like to get the dark notifications back when using arc-darker.

Just for clarification: In the screenshots you posted, the notifications are dark with `0.6.0`, and light with `0.4.4`. Did you post the screenshots the wrong way around?

**Comment by malnvenshorn** [comment]
> Did you post the screenshots the wrong way around?

Yes indeed. I updated my post.

**Comment by jnsh** [comment]
I added styling for xfce4-notifyd notifications in https://github.com/jnsh/arc-theme/commit/b7973a859d32eee7ea8e460b536759133719bb73 that addresses this. 

Please let me know if that results in any regressions, is missing features, or causes any other issues with the notifications.

**Comment by malnvenshorn** [comment]
What I've noticed is that the buttons are still white.

![Bildschirmfoto_2020-04-17_09-44-09](https://user-images.githubusercontent.com/13801805/79547451-36230000-8094-11ea-9ada-238ae0f2da8f.png)

**Comment by jnsh** [comment]
@malnvenshorn Thanks, I completely forgot about the buttons.

They should be now styled correctly with https://github.com/jnsh/arc-theme/commit/0779e1ca84141d8b443cf3e60b85307a145169b6.

**Comment by malnvenshorn** [comment]
Looks good now. Thank you :+1:

**Comment by jnsh** [comment]
I suppose this can be closed.

If you notice any other issues with the notifications, or anything else in general, please let me know. I'm not using xfce4 desktop myself, so it's always possible I've missed something obvious, even though I try to be thorough with my testing.

Thanks again.
