### ISSUE TITLE
Visual bug on title bars and clickable items

### ISSUE THREAD

**Issue by GoulvenC** [jnsh/arc-theme#39]
![](https://i.imgur.com/LoVioC8.png)

I really don't know anything about GTK, so help would be appreciated :/ I did not see any errors during the installation.

Distro -> Ubuntu 20.4
GTK -> 3.24.18-1ubuntu1
Gnome -> 3.36.1
Cinnamon -> 4.4.8-4

Find this issue on the old theme repo, with the same bug : https://github.com/horst3180/arc-theme/issues/924

**Comment by jnsh** [comment]
Thanks for the report.

How did you install the theme?

**Comment by GoulvenC** [comment]
I used the manual installation :) as explain here : https://github.com/jnsh/arc-theme/blob/master/INSTALL.md

**Comment by jnsh** [comment]
I really can't think how this could happen if the theme is built for the correct gtk3 version, and from this repo.

Can you make sure you haven't installed other versions of the Arc theme to `~/.themes`, `~/.local/share/themes` or `/usr/share/themes`.

Then make sure to pass the `--with-gtk3=3.24` option to `./autogen.sh` when building, if you didn't already.

If those didn't help, can you post the list of full commands you used for building and installing the theme.

**Comment by GoulvenC** [comment]
Works well better with the `--with-gtk3` option !

Thanks for your help :)
