### ISSUE TITLE
Can we get a compiled version not in a gresource?

### ISSUE THREAD

**Issue by gsbhasin123** [jnsh/arc-theme#40]
Here's my current dilemma:
I want to change the window buttons of arc. So I extract the gresource (and everything from it). Then I change the filepath to `gtk-main.css` , originally the resource path. Now all assets disappear! I mean when I launch a gtk 3 app like gtk3-widget-factory there are no checkboxes. Yes, the assets directory exists. But if I put my window button SVGs into the assets dir and insert the relevant code into gtk-main.css, those window buttons show but still not the other assets. Very very strange behavior. This would be simplified a lot by a version without gresource (if I can compile with a certain flag, please do tell).
thanks in advance

**Comment by jnsh** [comment]
Disabling the build time gresource compilation for the GTK3 theme is not currently possible. While it would be technically possible to add a build option for this, frankly I don't think it would be useful enough to be worth implementing.

Probably the best way to modify the theme would be editing it before compilation. This way you can also save your modifications as a separate git commit, and re-apply them easily any time you want to update and rebuild the theme.

You should also be able to edit the extracted gresource, and AFAIK it should work, as long as the asset paths are correct on the CSS. You could also try recompiling the theme into a gresource file after modifying. If you simply replace the old assets, this should work without any CSS modifications.

**Comment by gsbhasin123** [comment]
Thank you for your prompt response, @jnsh!
> Probably the best way to modify the theme would be editing it before compilation. This way you can also save your modifications as a separate git commit, and re-apply them easily any time you want to update and rebuild the theme.

True, but I'm not sure where I would change the window buttons, I'm more used to working with compiled gtk themes.

> You should also be able to edit the extracted gresource, and AFAIK it should work, as long as the asset paths are correct on the CSS. You could also try recompiling the theme into a gresource file after modifying. If you simply replace the old assets, this should work without any CSS modifications.

Yeah, this method works for every other theme but not here, very strange. The asset paths are correct. I'm not sure how to recompile into a gresource file, sadly

**Comment by jnsh** [comment]
> I'm not sure where I would change the window buttons

The build system generates the assets from the `asset.svg` file (see [HACKING.md](https://github.com/jnsh/arc-theme/blob/master/HACKING.md)). Using assets from other sources (i.e. if editing the `asset.svg` doesn't make sense) would probably require some more complex changes.

[This comment](https://github.com/arc-design/arc-theme/issues/186#issuecomment-495965639) may also be of some help.

> I'm not sure how to recompile into a gresource file, sadly

See `man glib-compile-resources` and/or search web for "compile gresource".

**Comment by gsbhasin123** [comment]
> The build system generates the assets from the asset.svg file (see HACKING.md). Using assets from other sources (i.e. if editing the asset.svg doesn't make sense) would probably require some more complex changes.

Awesome!!  My files are SVGs so I should be able to paste them in with inkscape - that should work. Probs easier than making a gresource. thank you! I'll reopen this if I hit any problems

**Comment by gsbhasin123** [comment]
Aw it failed.
```
Exporting only object with id="switch-active-insensitive-header-dark"; all other objects hidden.
Background RRGGBBAA: ffffff00
Area 429:25:481:49 exported to 52 x 24 pixels (96 dpi)
/bin/optipng -o7 --quiet "assets/switch-active-insensitive-header-dark.png"
/bin/inkscape --export-id-only --export-filename="assets/titlebutton-close-dark.png" --export-id="titlebutton-close-dark" --export-dpi=96 "assets.svg" >/dev/null
Failed to get connection
** (org.inkscape.Inkscape:12276): CRITICAL **: 15:43:43.753: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (org.inkscape.Inkscape:12276): CRITICAL **: 15:43:43.753: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (org.inkscape.Inkscape:12276): CRITICAL **: 15:43:43.753: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (org.inkscape.Inkscape:12276): WARNING **: 15:43:43.905: Fonts dir '/root/.config/inkscape/fonts' does not exist and will be ignored.
InkFileExport::do_export_png: Object with id="0" was not found in the document. Skipping.
/bin/optipng -o7 --quiet "assets/titlebutton-close-dark.png"
make[3]: *** [Makefile:566: assets/titlebutton-close-dark.png] Error 1
make[3]: Leaving directory '/home/codic/arc-theme/common/gtk-3.0/3.24'
make[2]: *** [Makefile:456: install-recursive] Error 1
make[2]: Leaving directory '/home/codic/arc-theme/common/gtk-3.0'
make[1]: *** [Makefile:465: install-recursive] Error 1
make[1]: Leaving directory '/home/codic/arc-theme/common'
make: *** [Makefile:363: install-recursive] Error 1
```

I used this svg:
[assets.svg.txt](https://github.com/jnsh/arc-theme/files/4618841/assets.svg.txt)
Renamed to `.svg.txt` so I can upload to github

**Comment by jnsh** [comment]
Did you take note of this (in HACKING.md)?
> - Find the object you want to edit and make your changes. **Important: Don't change the object id!**

**Comment by gsbhasin123** [comment]
Nope I used inkscape and jut pasted them in
 How owuld I keep the ids?  :sweat_smile:

**Comment by jnsh** [comment]
This may be getting beyond the scope of this issue tracker, but basically you either edit the object with the existing id, or remove the old object and add new object with the same id.

If you can't figure it out, e.g. inkscape's support channels may be more appropriate place to seek assistance for this.

**Comment by gsbhasin123** [comment]
Thank you, closing this issue.
