### ISSUE TITLE
Build error - missing canberra-gtk-module

### ISSUE THREAD

**Issue by veskoaleksandrov** [jnsh/arc-theme#42]
First and foremost big thanks for maintaining our beloved arc-theme. 

I ran into following message:  
> Failed to load module "canberra-gtk-module"
 
while attempting to build the theme system wide, Ubuntu 18.04 LTS. Quick research shows following libraries need to be installed first: 
- libcanberra-gtk-module 
- libcanberra-gtk3-module
(not installed out of the box on my system)

The message was gone after running: 
`sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`

Hopefully sharing my experience will help others. Perhaps it is worth mentioning the libcanberra modules in INSTALL.md?

**Comment by jnsh** [comment]
libcanberra is certainly not required for building, but could be a dependency for one or more of the arc-theme build dependencies (impossible to tell which one without the full build error log).

Your distribution's package manager should make sure all package dependencies are met, so I'm assuming this is an packaging issue, and therefore has nothing to do with the theme.

Thank you for the report regardless.
