### ISSUE TITLE
Implement styling for libhandy

### ISSUE THREAD

**Issue by johnfactotum** [jnsh/arc-theme#45]
Current:
![image](https://user-images.githubusercontent.com/50942278/82826854-6c2a7f80-9e9d-11ea-8af8-fe38bfdcd7af.png)

Expected:
![image](https://user-images.githubusercontent.com/50942278/82826918-84020380-9e9d-11ea-8a61-58045249fe44.png)

Adwaita, for reference:
![image](https://user-images.githubusercontent.com/50942278/82826826-603ebd80-9e9d-11ea-8e98-c2e5d44b28d5.png)

Screenshots from GNOME Clocks 3.36.2

**Comment by jnsh** [comment]
Thank you for pointing this out.

I'll implement the styling for the whole libhandy at some point. Doesn't really make sense to only fix this single widget/instance.

**Comment by jnsh** [comment]
Updated the title to be more clear about libhandy, to avoid duplicate issues.

**Comment by Alexmitter** [comment]
I add some screenshots of the Arc Theme on Phosh and one Adwaita reference to see the differences. Please notice that for the shell itself, Phosh currently automatically always pics the dark theme.
![store-adwaita](https://user-images.githubusercontent.com/6940479/84769821-c4edc380-afd6-11ea-8b4f-2331a4605164.png)
![store-arc](https://user-images.githubusercontent.com/6940479/84769826-c8814a80-afd6-11ea-82fc-e80b77397953.png)
![store-arc-dark](https://user-images.githubusercontent.com/6940479/84769831-cae3a480-afd6-11ea-804e-64080229371b.png)
![store-arc-darker](https://user-images.githubusercontent.com/6940479/84769837-cdde9500-afd6-11ea-9db8-62e585893fcb.png)

**Comment by jnsh** [comment]
From what I gathered, Phosh theme is a separate thing, and has nothing to do with libhandy styling. 

Please open a separate issue, if you'd like to discuss about Phosh theming. Although I can say that I can't promise to support Phosh in addition to the workload of every currently supported theme, unless there are willing contributors that can commit to the continuous development, maintenance and testing for it.

**Comment by Alexmitter** [comment]
Hello @jnsh, the Phosh Shell is basically just normal GTK3(afaik). But some parts of seem hard-coded to certain colors. And the shell always uses the dark theme, so if you select Adwaita, it will use Adwaita:dark for the shell, if you select Arc it will use Arc-Dark.
Phosh with the standard adwaita theme:
![phosh-adwaita](https://user-images.githubusercontent.com/6940479/84803213-fc259a00-b001-11ea-96a2-ae3d05dcd67d.png)
Phosh with Arc:
![phosh-arc](https://user-images.githubusercontent.com/6940479/84803298-1fe8e000-b002-11ea-859e-e4aea0823010.png)

>  Although I can say that I can't promise to support Phosh in addition to the workload of every currently supported theme
To do anything right now wasted time, Phosh is still under heavy development and things can change massively. So please do not take any actions. This is purely to show how Arc theme currently performs in the phone context and how those libhandy widgets currently look on the phone with Arc.

**Comment by jnsh** [comment]
https://github.com/jnsh/arc-theme/commit/11446048b45e68eaac7c4b7baef54d77d1ef3ed0 fixes the padding for the HdyViewSwitcherBar actionbar. On libhandy 0.0.13 there are few other remaining visual issues that can't be fixed, as the default libhandy stylings can't be overridden.

Starting from libhandy 0.80.0 or 0.81.0, a fallback theme is used, which results in libhandy widgets looking inconsistent with Arc. This will be fixed in the future by implementing a full libhandy styling.
