### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by vexillia** [jnsh/arc-theme#46]
Install fails with this message:
`autogen.sh: 10: autoreconf: not found`

**Comment by jnsh** [comment]
Please make sure all the build dependencies, listed in the [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md#build-dependencies), are installed on your system.

**Comment by vexillia** [comment]
Done

`./autogen.sh --prefix=/usr`

Runs with this error:

`configure: error: Could not determine GTK3 version. Install GTK3 (and its development files), or use the --with-gtk3=<version> option. Alternatively you can choose to not build the GTK3 theme with --disable-gtk3 option.`

Running xubuntu 20.04.

**Comment by vexillia** [comment]
OK I get it I now need to install inkscape, optipng & sassc just to install a theme.

**Comment by jnsh** [comment]
Yes, they are needed for building certain parts of the theme from source.

If you want to avoid building, there's also a package for debian, that *should* work on ubuntu 20.04, although I'm not the packager, and can't give no guarantees or support for it. The package is listed on the [README.md](https://github.com/jnsh/arc-theme/blob/master/README.md) of this project.

**Comment by vexillia** [comment]
Thanks deb worked fine.  Wish I seen it earlier.
