### ISSUE TITLE
Some text is way too huge

### ISSUE THREAD

**Issue by NoXPhasma** [jnsh/arc-theme#48]
### Details

With the current HEAD, the fonts of several elements are way too huge. Here are comparison of how it looks with this theme and how it looks with Mint Y Dark, both with the same font size of 11px.

arc-theme dark:
![acr1](https://user-images.githubusercontent.com/7719590/83359154-ae116500-a378-11ea-89d1-0d7fe387b46e.png)
![arc2](https://user-images.githubusercontent.com/7719590/83359156-b23d8280-a378-11ea-854c-3785aae33110.png)

Mint Y Dark:
![minty1](https://user-images.githubusercontent.com/7719590/83359164-bd90ae00-a378-11ea-94ef-1158324f73fc.png)
![minty2](https://user-images.githubusercontent.com/7719590/83359167-bff30800-a378-11ea-811c-da097a805dfe.png)

This also affects text in desklets.

Please add the following information:

- Distribution and version: Manjaro 20.0.1
- Versions for the affected applications/desktops/tookits: Cinnamon 4.6.2

**Comment by jnsh** [comment]
Thank you for the report.

Cinnamon 4.6 default theme removed all hardcoded font sizing, and I implemented equivalent change for Arc in https://github.com/jnsh/arc-theme/commit/e9fad953b9754a5758c57747c4971d52fa00221b. This improves the consistency within the theme, and I think one would expect that the font size setting should actually change the font-size across the whole theme.

I'm quite sure what's happening here is that the notifications etc. previously used a hardcoded 9pt font-size. Now with the aforementioned change, the notification font-size is based on your configuration, which in this case is 11pt.

I don't think there's objective reason to consider the font-size on your screenshots too large either, although I can understand how the size difference compared to previous version seems quite striking.

If you think there are other elements where the font change causes issues, or looks bad please let me know and I can look at it. It is possible to set the font-sizes for individual elements to e.g. 80% of the configured font size, which could work better in some areas. However, I think the notification font-size is not an issue, and shouldn't be changed.

**Comment by NoXPhasma** [comment]
The larger font seems to affect most of what has to do with the panel and desktop. No application seems to be affected. 

Another case where it is much larger and feels really unpleasant is the context menu of the panel and the applets.:
![arc3](https://user-images.githubusercontent.com/7719590/83365682-3d833c00-a3aa-11ea-9743-fbf1ba3dd68d.png)
![minty3](https://user-images.githubusercontent.com/7719590/83365685-407e2c80-a3aa-11ea-905f-b223397cf073.png)

**Comment by jnsh** [comment]
Yes, the change only affects the cinnamon shell, i.e. the panel, notifications etc, and not the applications. Now the shell uses the same font size as the applications, which is the most consistent option.

Again, I fail to see any real issue with the panel context menu screenshots, other than one's personal preference. If you like the fonts smaller you can adjust the "default font" size from cinnamon settings.

Just in case there's confusion, the Arc cinnamon theme isn't based on the Mint-X/Y themes but the default "cinnamon" theme, and you should use it for the comparison.

**Comment by NoXPhasma** [comment]
>If you like the fonts smaller you can adjust the "default font" size from cinnamon settings.

Unfortunately that would make the font size in all applications too small for me, as the font is larger in the shell as in the rest of the applications.

> Just in case there's confusion, the Arc cinnamon theme isn't based on the Mint-X/Y themes but the default "cinnamon" theme, and you should use it for the comparison.
Yeah it's actually the same in Cinnamon theme as in Arc. So I guess this is an upstream issue.

**Comment by jnsh** [comment]
> Unfortunately that would make the font size in all applications too small for me, as the font is larger in the shell as in the rest of the applications.

I don't understand this. The font should be exactly the same size in the shell and applications (apart from some specific elements).

> Yeah it's actually the same in Cinnamon theme as in Arc. So I guess this is an upstream issue.

AFAICT, this is an intentional change from upstream. If upstream changes this, I'm inclined to change the Arc cinnamon theme as well.

**Comment by NoXPhasma** [comment]
Yes, I explained it wrong, the font size is actually the same, but before it was smaller. And now the menus and notifications feel really huge.

To give you an impression why it bothers me so much, I now have to move my mouse over almost the whole screen in some menus, like this:
![Screenshot_2020-06-01_02-38-19](https://user-images.githubusercontent.com/7719590/83366698-1714cf00-a3b1-11ea-9738-d19295007d14.png)

Anyway, I will raise my complain upstream.

**Comment by jnsh** [comment]
I see. One thing specific to the `popup-menu-item`s is that their padding is relative to the font size as well, so bigger font results in larger paddings, increasing the menu height even more.

I suppose the best solution would be being able to change the shell font size individually from the applications, if that could be implemented upstream.

As a personal workaround you could revert the commit that changed the fonts. If you're using the AUR package, it's quite simple to do this in the `PKGBUILD` by adding something like the following before the `build()` (not tested, but this should work unless I'm forgetting something):

```
prepare() {
  cd "${_pkgname}"
  git revert e9fad953b9754a5758c57747c4971d52fa00221b
}
```

**Comment by NoXPhasma** [comment]
I tried that and it gave me a message about the revert, but it didn't work. That probably didn't really reverted that commit.

**Comment by smurphos** [comment]
@NoXPhasma - it's straightforward to revert to theme controlled font characteristics. In the installed theme just open the cinnamon.css file, locate the stage {} declaration and add back in a  `font-size:` declaration and optionally a `font-family:` declaration. A hardcoded declaration here will trump the system default theme, and the rest of the theme will scale as per the scalable font-size: declarations in the rest of the theme.

**Comment by NoXPhasma** [comment]
@smurphos That works pretty well, thank you.

**Comment by jnsh** [comment]
Indeed the font properties for the `stage` element are the part that sets the global font. It may also be a bit more robust workaround than reverting the commit. Thanks for chiming in @smurphos.

The `git revert` in the PKGBUILD should work as well, but by default it tries to open text editor for the revert commit message, which is a bit confusing and could cause issues. I added the `--no-edit` flag to my above example that prevents this.

**Comment by NoXPhasma** [comment]
I'm using the approach of smurphos, as it is the less invasive. I just created a new `cinnamon.css` file `~/.themes/Arc-Dark/cinnamon/` with this content:
```
@import url("/usr/share/themes/Arc-Dark-solid/cinnamon/cinnamon.css");

stage {
  font-size:0.9em;
}
```
With his I don't need to edit anything.
