### ISSUE TITLE
Increase close button clickable area

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [jnsh/arc-theme#50]
Hi there!

I'm using this theme on a 4k display, and we all know that Gnome (and many other Linux DE's) lacks good support for HiDPI resolution. One thing that bothers me is the close button clickable area. In order to click the close button I have to reach the cursor inside that red circle icon, and that circle is very tiny on a 4k display. Even on regular 1080p display it's not that easy to click on that button.

On the image bellow we can see that the "More option" button actually has a good and square clickable area, while the close button doesn't.

![image](https://user-images.githubusercontent.com/12160864/83553671-eb453680-a4e1-11ea-8f3f-f333bb88e2e1.png)

So here is my question. Have you considered a close button overhaul? I mean, this round close button seems dated, and there are better design for close buttons like those in Google Chrome and VS Code. They have prominent "X" buttons that are easy to reach. If a redesign is out of question, would be possible to make the clickable area a square, just like the "More option" button?

Also, thank you for continuing support this theme. Some now and then I try new themes, and always come back to Arc.

**Comment by jnsh** [comment]
Hi, and thank you for the suggestion.

I can certainly understand the problem with the clickable area for the window control buttons being very small, especially if you're using the theme on HiDPI display without scaling.

However, the visual style of the original Arc theme won't be altered in this fork, and the window control buttons can't really be changed for that reason.

Arc theme has always had a more compact design, not necessarily best suited for HiDPI, and I don't think there's much chance for changing that without major alterations to the overall style. If things look too small for you, the "right" way fix this is to use display scaling. I was under the impression that it worked fine on GNOME these days, but if it doesn't, I don't think it should be attempted to work around by changing the theme either.

I think it might be possible to increase the clickable area to extend even more outside of the visual icons (currently there's 4px padding outside of the icons that can be clicked), at least for the GTK3 window controls, which should make them easier to click. I'll try to investigate this at some point.

You can also adjust the GTK3 window control buttons style for yourself via `~/.config/gtk-3.0/gtk.css`. [This example](https://github.com/arc-design/arc-theme/issues/186#issuecomment-495965639) might be of some help. Please share if you think of any good alternative styles, or have any other ideas for this.

**Comment by johnfactotum** [comment]
Fractional scaling in GNOME works pretty well on Wayland now.

For big, Windows style window buttons, there's [Qogir](https://github.com/vinceliuice/Qogir-theme), which is based on and visually similar to Arc.

**Comment by rafaelrenanpacheco** [comment]
> Fractional scaling in GNOME works pretty well on Wayland now.

Indeed, but [not for NVIDIA](https://www.reddit.com/r/linuxquestions/comments/8q1ko0/why_cant_existing_nvidia_drivers_be_used_with/) users.

> For big, Windows style window buttons, there's Qogir, which is based on and visually similar to Arc.

Nice, I'll try that, thanks for the suggestion!

Best regards,
Rafael Pacheco.

**Comment by jnsh** [comment]
Please don't close the issue yet.

Even if it's not a problem for you anymore if you switched to another theme, it may still be a problem for other Arc users. This is something I'd like to attempt to improve in the future, and I'd prefer to keep the issue open as a reminder.

**Comment by TerrorSquad** [comment]
Hi,

Are there any new updates regarding this issue?

I'm using Linux Mint 20.3 with the following theme settings:
Window borders: Adapta
Controls: Arc
Desktop: Arc

1440p resolution on a 27" monitor with no scaling.
I did change the Window Title Font to 20 in order to increase the min, max, close button sizes. They're kinda okay now, but I still wish they were bigger. There is that padding around the buttons, but I'd rather have a larger button compared to a small button with extra padding. Increasing the font will make the window title a lot larger compared to the buttons, so it's not really an optimal solution.

I had to use Adapta window borders to increase the sizes of the buttons since they're tiny within the Arc theme.

There are some windows that still use min, max, close buttons from Arc, such as the window for opening a compressed archive e.g. a zip file. The buttons are super small and really hard to click.

I really like this theme as it's really similar to One Dark which I use in Phpstorm and VS Code.
The colors and the overall design language are amazing. The only thing bothering me is the size of the window buttons.

If we could get bigger buttons this would be the best theme on the market.

**Comment by jnsh** [comment]
As I explained earlier, the window title buttons can't be changed without changing the overall design of the theme, so I won't be doing that. I did also attempt adding transparent padding around the buttons in GTK decorations, to increase the clickable area, but that didn't really help either without changing the appearance of the theme.

As a (partial) workaround, GTK title buttons can be adjusted to increase their size for single user, by injecting updated CSS to the user's `~/.config/gtk-*/gtk.css` files. Unfortunately this only works with GTK based decorations, i.e. mutter/gnome-shell and GTK client side decorations.

Changing window decorations that aren't themed with GTK, e.g. metacity (i.e. Cinnamon, MATE) and Xfwm4 would require changes to their source SVG files (and maybe other places).

Below are GTK theme CSS snippets for each theme variant, that change the GTK titlebar buttons to look more or less like standard, round, headerbar buttons. Copy one of these to your user's `~/.config/gtk-3.0/gtk.css` and/or `~/.config/gtk-4.0/gtk.css`, and the buttons are changed immediately for newly started applications.

![Screenshot from 2021-12-06 18-01-42](https://user-images.githubusercontent.com/39574454/144884298-fee917c4-3522-416c-be3f-cf2eac841558.png)

**Arc and Arc-Lighter (and the -solid variants):**

GTK 3:
```
button.titlebutton {
  background-image: none;
  color: rgba(82, 93, 118, 0.8);
  outline-offset: -3px;
  background-color: rgba(231, 232, 235, 0);
  border-color: rgba(231, 232, 235, 0); }

button.titlebutton:not(.appmenu) {
  border-radius: 9999px;
  border-width: 1px;
  min-height: 26px;
  min-width: 26px;
  margin-top: 2px;
  margin-bottom: 2px;
  padding: 0; }

button.titlebutton:hover {
  color: rgba(82, 93, 118, 0.8);
  border-color: rgba(82, 93, 118, 0.1);
  background-color: rgba(251, 251, 252, 0.9); }

button.titlebutton:active,
button.titlebutton:checked {
  color: #ffffff;
  border-color: #5294e2;
  background-color: #5294e2; }

button.titlebutton.close:active,
button.titlebutton.close:checked {
  color: white;
  border-color: #F27835;
  background-color: #F27835; }
```
GTK 4:
```
windowcontrols button {
  background-image: none;
  color: rgba(82, 93, 118, 0.8);
  outline-offset: -3px;
  background-color: rgba(231, 232, 235, 0);
  border-color: rgba(231, 232, 235, 0); }

windowcontrols button:not(.appmenu) {
  border-radius: 9999px;
  border-width: 1px;
  min-height: 26px;
  min-width: 26px;
  margin-top: 2px;
  margin-bottom: 2px;
  padding: 0; }

windowcontrols button:hover {
  color: rgba(82, 93, 118, 0.8);
  border-color: rgba(82, 93, 118, 0.1);
  background-color: rgba(251, 251, 252, 0.9); }

windowcontrols button:active,
windowcontrols button:checked {
  color: #ffffff;
  border-color: #5294e2;
  background-color: #5294e2; }

windowcontrols button.close:active,
windowcontrols button.close:checked {
  color: white;
  border-color: #F27835;
  background-color: #F27835; }
```

**Arc-Dark and Arc-Darker:**

GTK 3:
```
button.titlebutton {
  background-image: none;
  color: rgba(207, 218, 231, 0.8);
  outline-offset: -3px;
  background-color: rgba(47, 52, 63, 0);
  border-color: rgba(47, 52, 63, 0); }

button.titlebutton:not(.appmenu) {
  border-radius: 9999px;
  border-width: 1px;
  min-height: 26px;
  min-width: 26px;
  margin-top: 2px;
  margin-bottom: 2px;
  padding: 0; }

button.titlebutton:hover {
  color: rgba(207, 218, 231, 0.8);
  border-color: rgba(21, 23, 28, 0.37);
  background-color: rgba(95, 105, 127, 0.37); }

button.titlebutton:active,
button.titlebutton:checked {
  color: #ffffff;
  border-color: transparent;
  background-color: #5294e2; }

button.titlebutton.close:active,
button.titlebutton.close:checked {
  color: white;
  border-color: transparent;
  background-color: #F27835; }
```
GTK 4:
```
windowcontrols button {
  background-image: none;
  color: rgba(207, 218, 231, 0.8);
  outline-offset: -3px;
  background-color: rgba(47, 52, 63, 0);
  border-color: rgba(47, 52, 63, 0); }

windowcontrols button:not(.appmenu) {
  border-radius: 9999px;
  border-width: 1px;
  min-height: 26px;
  min-width: 26px;
  margin-top: 2px;
  margin-bottom: 2px;
  padding: 0; }

windowcontrols button:hover {
  color: rgba(207, 218, 231, 0.8);
  border-color: rgba(21, 23, 28, 0.37);
  background-color: rgba(95, 105, 127, 0.37); }

windowcontrols button:active,
windowcontrols button:checked {
  color: #ffffff;
  border-color: transparent;
  background-color: #5294e2; }

windowcontrols button.close:active,
windowcontrols button.close:checked {
  color: white;
  border-color: transparent;
  background-color: #F27835; }
```

**Arc-Dark-solid and Arc-Darker-solid:**

GTK 3:
```
button.titlebutton {
  background-image: none;
  color: rgba(207, 218, 231, 0.8);
  outline-offset: -3px;
  background-color: rgba(47, 52, 63, 0);
  border-color: rgba(47, 52, 63, 0); }

button.titlebutton:not(.appmenu) {
  border-radius: 9999px;
  border-width: 1px;
  min-height: 26px;
  min-width: 26px;
  margin-top: 2px;
  margin-bottom: 2px;
  padding: 0; }

button.titlebutton:hover {
  color: rgba(207, 218, 231, 0.8);
  border-color: rgba(21, 23, 28, 0.4);
  background-color: rgba(95, 105, 127, 0.4); }

button.titlebutton:active,
button.titlebutton:checked {
  color: #ffffff;
  border-color: transparent;
  background-color: #5294e2; }

button.titlebutton.close:active,
button.titlebutton.close:checked {
  color: white;
  border-color: transparent;
  background-color: #F27835; }
```
GTK 4:
```
windowcontrols button {
  background-image: none;
  color: rgba(207, 218, 231, 0.8);
  outline-offset: -3px;
  background-color: rgba(47, 52, 63, 0);
  border-color: rgba(47, 52, 63, 0); }

windowcontrols button:not(.appmenu) {
  border-radius: 9999px;
  border-width: 1px;
  min-height: 26px;
  min-width: 26px;
  margin-top: 2px;
  margin-bottom: 2px;
  padding: 0; }

windowcontrols button:hover {
  color: rgba(207, 218, 231, 0.8);
  border-color: rgba(21, 23, 28, 0.4);
  background-color: rgba(95, 105, 127, 0.4); }

windowcontrols button:active,
windowcontrols button:checked {
  color: #ffffff;
  border-color: transparent;
  background-color: #5294e2; }

windowcontrols button.close:active,
windowcontrols button.close:checked {
  color: white;
  border-color: transparent;
  background-color: #F27835; }
```

Unfortunately I don't think there's anything else that could be done about this, so I'm going to close this issue.

However, feel free to continue discussion, if there are any further suggestions. Also please let me know if there are any issues with the above CSS snippets, or if you have any suggestions for improvements for them.

**Comment by TerrorSquad** [comment]
Thanks for the snippets. I'm using the Cinnamon edition of Mint, so I guess I'd need to change the metacity XML files.

I think you should seriously reconsider the decision to not touch the theme in order to preserve the visual identity. Please explain how will the bit larger buttons alter the visual style in a major way? It's not like changing the actual color scheme, or shadows.

Besides, software is always evolving and so are the various themes and UI components inside all OSes, browsers, apps, you name it. So is the hardware, monitor sizes, and display resolutions.

Form should not hinder function. The window controls were probably usable on lower resolutions, but they're not on higher ones - 2k and above. Why can't the buttons get just a bit bigger, in order for us - humans - actual users of the theme, not to have to squint our eyes or be surgically precise with our mice while chasing the close or the minimize button?

**Comment by jnsh** [comment]
Sorry, I've put lot of thought on my choice to not change the design, and explained my views on many occasion, so I have no interest on discussing it further.

The buttons are part of original design, from the original author, and I want to respect that. They are distinct part of the theme, and some people would be displeased if they were changed. If anyone wants to change them, they are free to do it for themselves, or in a separate fork.
