### ISSUE TITLE
Libhandy bottom controlls not matching top controlls.

### ISSUE THREAD

**Issue by Alexmitter** [jnsh/arc-theme#53]
Libhandy introduced header bar controls that move to the bottom if window is too narrow.
Those bottom buttons exactly match the buttons that would be in the header bar in Adwaita.
In Arc those buttons do not match. Also, those libhandy apps display a few pixel high bar at the bottom, even if the Libhandy controls are currently in the header bar. Adwaita does not do that.

I made a small clip better showing the issue: https://youtu.be/wjfmA9DCdw0

Solving that issue is important for using the Arc Theme with the Pinephone/Phosh

**Comment by jnsh** [comment]
Thank you for the report.

There was already an [open issue]( https://github.com/jnsh/arc-theme/issues/45) for this, although it being about libhandy wasn't very obvious from its title. Please continue discussion there if there's anything to add.

I'm hoping to add full styling for libhandy in the future, but it's not the top priority ATM.

Closing this as a duplicate
