### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by mahmutelmas06** [jnsh/arc-theme#54]
I runned

sudo ./autogen.sh --prefix=/usr

and after

sudo make install

than i got this error

make: *** No rule to make target 'install'. Stopped.

**Comment by jnsh** [comment]
My guess is that the `autogen.sh` command didn't complete succesfully, and therefore there's no `Makefile`. Please check the `autogen.sh` output for errors.

I'm assuming you already did read [install instructions](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md). It should explain building and common issues in detail.

**Comment by jnsh** [comment]
Since there's been no additional comments, I'm closing this with the assumption that the problem got sorted some way.
