### ISSUE TITLE
Issue when building from source (Ubuntu/Cinnamon)

### ISSUE THREAD

**Issue by AKushWarrior** [jnsh/arc-theme#55]
Seeing as there is no pre-built binary for Ubuntu, I am trying to build it from source.

I use the cinnamon desktop, so I ran this:
```
root@redacteduser:/home/redacteduser/arc-theme# ./autogen.sh --prefix=/usr --disable-gnome-shell --disable-gtk3 --disable-gtk2 --disable-xfwm
```

It failed with this log:
```
me-shell --disable-gtk3 --disable-gtk2 --disable-xfwm
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether ln -s works... yes
checking for cinnamon... yes
Detected Cinnamon 4.4.8
Building Cinnamon theme 4.4
checking for sassc... /usr/bin/sassc
checking that generated files are newer than configure... done
configure: error: conditional "INKSCAPE_1_0_OR_NEWER" was never defined.
Usually this means the macro was only invoked conditionally.
```
I have autoconf, automake, pkgconf, and sassc installed. Cinnamon is working.

**Comment by AKushWarrior** [comment]
Edit: I also have tried this with the latest build of Inkscape installed. The same issue persists.

**Comment by jnsh** [comment]
Thanks for the report. This is a bug in the build system, I'll try to figure out a fix ASAP.

In the meanwhile, the configure script should finish if you enable building for either the GTK2, GTK3 or XFWM theme.

As a side note, the debian bullseye package _should_ work on Ubuntu 20.04.

**Comment by AKushWarrior** [comment]
I haven't tested the debian bullseye package. I'll try that, then play around some more with the build script.

Thanks for the prompt reply, and thanks for taking up maintenance of this theme.

**Comment by AKushWarrior** [comment]
Update: bullseye works fine.

You can keep this issue open for tracking purposes, I suppose.
