### ISSUE TITLE
Addition of Arc Darkest

### ISSUE THREAD

**Issue by philipzae** [jnsh/arc-theme#57]
Would be useful to include this other darker variant of Arc-Dark
https://www.gnome-look.org/p/1317409/

**Comment by jnsh** [comment]
Thanks for the suggestion, but this won't be implemented here.

Anything that changes the theme colors should be done in a separate fork. All current theme variants are using the same color palette and it won't be changed for single variant (or for any other reason ever).

**Comment by philipzae** [comment]
Thanks for the reply. Does the theme colors not have a darker color than what is used in Arc-Dark that could be used to create a darker version?

**Comment by jnsh** [comment]
It's not a matter of single darker color, but you'd need a complete darker color scheme.

Even if there was a simple way to do it, I think this is out of the scope of this project.
