### ISSUE TITLE
Nautilus file open/save dialogue glitch

### ISSUE THREAD

**Issue by AlexKF98** [jnsh/arc-theme#60]
I'm using Fedora 32, and installed the theme from source. When using Arc-Darker, if I try to save a file, or open a file, with Firefox or Chromium, the bottom of the Nautilus dialogue is white and the file type selection is grey.

![Captura de tela de 2020-07-11 14-20-45](https://user-images.githubusercontent.com/12222211/87229935-b9e24500-c382-11ea-963d-89c4f801f428.png)

**Comment by dartman** [comment]
I'm experiencing this issue as well.  I'm running Xfce on Manjaro (GTK 3.24.21) and, after compiling from source, the file-type chooser in the lower left is gray in the Arc and Arc-Darker themes. The other two themes are unaffected. Clicking into this box to display the list of file types works, but its default state is grayed out.

I've been trying to solve this on my own for a few days (and will continue to) but everything I know about gtk and themes, I've learned on the way to creating this post.
 
![Arc_Theme_Screenshot_1](https://user-images.githubusercontent.com/6021996/87743797-c1a54d80-c7b7-11ea-81e5-3a07a428a5a6.png)
![Arc_Theme_Screenshot_2](https://user-images.githubusercontent.com/6021996/87743798-c1a54d80-c7b7-11ea-9b92-e59538fc79ad.png)

**Comment by jnsh** [comment]
I confirmed this earlier as well. I'll try to figure out a fix soon.

**Comment by jnsh** [comment]
This was a regression from a recent change, and should be fixed with the above commit.
Thank you for the bug reports :)
