### ISSUE TITLE
Take Over arc-theme Fedora Package [Fedora 32]

### ISSUE THREAD

**Issue by hozza** [jnsh/arc-theme#62]
### Issue

It looks like the [arc-theme package on Fedora](https://src.fedoraproject.org/rpms/arc-theme) is out of date and not using this repo as the upstream source.

### Description

The Fedora package lists the @NicoHood [repo](https://github.com/NicoHood/arc-theme) (now renamed/[redirected](https://github.com/arc-design/arc-theme) to @arc-design) as the source, now outdated, last update ages ago but still being used for rebuilds for each new Fedora version. 

@arc-design / @NicoHood arc-theme repo recommends this repo as the new actively maintained upstream.

There's a recent bug report of this outdated upstream issue reported at 2020-04-09 13:50 UTC by Fredrik Blomqvist: https://bugzilla.redhat.com/show_bug.cgi?id=1822634 _(there is another upstream request [here](https://bugzilla.redhat.com/show_bug.cgi?id=1753897), still marked as new, but it should be disregarded as it's outdated)_

### Fedora Repo Package Maintainer

A user called besser82 is set as the maintainer on the Fedora repo, the [besser82 fedora repo profile is linked here](https://src.fedoraproject.org/user/besser82/) - although there have been [unresponsive maintainer reports](https://bugzilla.redhat.com/show_bug.cgi?id=1610811) in the past since besser82 has been busy.

### Possible Solutions

It looks like besser82 and is active on GitHub under the same username! @besser82 Are you able to make this repo the upstream for the arc-theme Fedora package or could you had over the maintainer responsibility to @jnsh (if jnsh wants it?)

I'm not sure about how to maintain a package myself or how transfer maintainer of Fedora packages but it may have something todo with [orphaning the fedora package](https://fedoraproject.org/wiki/Orphaned_package_that_need_new_maintainers) then taking over as maintainer if besser is unresponsive.

### Update arc-theme Install Instruction to include Fedora

We could then update the README to include the Fedora package in the install instructions also.

**Comment by jnsh** [comment]
Thank you for the report, but this is a Fedora packaging issue and directly nothing to do with this upstream project. I usually couldn't, and will not take responsibility of maintaining distribution packages, especially for distros I'm not actively using myself.

If there's actively maintained Fedora package that is built from this project repo, I'm glad to add it to the list on the README. Other than that, I don't think there's much I could do here.

I'm closing this issue, but feel free to continue discussion here if it's of any help.
