### ISSUE TITLE
Thicker borders for xfwm

### ISSUE THREAD

**Issue by philipzae** [jnsh/arc-theme#63]
I'm running Xubuntu 20.04 and Xfwm does not handle window resizing well when themes have small borders. Arc has 2px borders, which is better than a number of other themes that only have 1px, but this should be increased to atleast 5px. The additional 3px will be of the same color as the window background, so it still seems that it has the same 2px border.

The changes that are needed are to the left, bottom-left, right, bottom-right, and bottom images.

In [this video](https://i.imgur.com/AD8pcCB.mp4), I demonstrate the difference between how easy it is to resize with a 5px compared to Arc.

**Comment by philipzae** [comment]
Examples from other themes.
https://github.com/adapta-project/adapta-gtk-theme/pull/746
https://github.com/shimmerproject/Greybird/pull/271

**Comment by jnsh** [comment]
Looks like the default xfwm4 theme [is using 4px borders](https://gitlab.xfce.org/xfce/xfwm4/-/commit/a4dccd1a22af60836c62a54f4e8d0e53dbe795d0), and I'm inclined to use the same width for Arc.

I might just do a full refactor for the xfwm4 theme against upstream at some point, and hopefully add the hidpi variants while I'm at it. However, there's a bunch of more important work to be done, so it may be awhile until I have time to look at it.
