### ISSUE TITLE
Help with colour pallette

### ISSUE THREAD

**Issue by osdamv** [jnsh/arc-theme#79]
Hello,

I found this theme for [firefox](https://github.com/rafaelmardojai/firefox-gnome-theme) , It make Firefox  looks more like an gnome application, However it do not support other themes beside adwaita. After some research looks like the changes are easy enough, it is only matter of change [2 CSS](https://github.com/rafaelmardojai/firefox-gnome-theme/tree/master/theme/colors). But I do not the color pallette for this theme, Can some give some pointers of where can I see the color pallet ?

Thanks!

**Comment by jnsh** [comment]
There's no common file that had a complete list of colors for all themes.

For SASS based themes (e.g. gtk3 which should be most relevant in this case), see `common/<theme>/<version>/sass/_colors.scss`. For the rest, you'd have to dig for the colors from the source files, or SVG assets.

Closing this as a non-issue for the theme, but feel free to continue discussion here if you have other questions or anything else to add.
