### ISSUE TITLE
Gnome 3.38 Calendar Events

### ISSUE THREAD

**Issue by Ugzuzg** [jnsh/arc-theme#84]
### Details
Calendar events are using styles from the adwaita theme.

- Distribution and version:
    Arch Linux
    arc-gtk-theme 20200819

- Versions for the affected applications/desktops/tookits:
    Gnome 3.38.1

![Screenshot from 2020-10-06 21-52-42](https://user-images.githubusercontent.com/1078004/95253552-d4f81000-081e-11eb-9090-782dd086b9bb.png)

**Comment by jnsh** [comment]
This is already fixed with https://github.com/jnsh/arc-theme/commit/175a3f3228e0714ee44c63fefcea2af51b41f765, which will be included in the next release.

If you don't want to wait, you can use `arc-gtk-theme-git` from AUR.

**Comment by Ugzuzg** [comment]
Had to change [this line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arc-gtk-theme-git#n24) to build the correct version.

**Comment by jnsh** [comment]
Correct, I should bump the gnome-shell version on the PKGBUILD.
Thank you for the reminder :)
