### ISSUE TITLE
Any chance to update the arc theme flatpak?

### ISSUE THREAD

**Issue by Alexmitter** [jnsh/arc-theme#86]
Hello

The flatpak seems to be still based on the old fork and not updated for a long while. Any chance of taking the flatpak definition repo for Arc Theme over? https://github.com/flathub/org.gtk.Gtk3theme.Arc-Dark

**Comment by jnsh** [comment]
Hello,

You should request this from the flathub package maintainer. I think you can simply open an issue to the github project you linked. I don't think there's any reason to believe the package was abandoned either. Even if that was the case, I really can't provide any binary packages myself, at least for distributions/packaging systems I'm not using myself.

Closing as a downstream packaging issue.
