### ISSUE TITLE
Windows jump when entering & leaving shell overview

### ISSUE THREAD

**Issue by keynslug** [jnsh/arc-theme#87]
### Before submitting

- [x] Make sure you have built the correct theme versions for gtk3, gnome-shell and cinnamon themes.

    I'm running Gnome Shell 3.38.1 under Wayland, installed from Arch repos. The `arc-theme` package built manually, here's excerpt from `config.log`:
    ```
    configure:2951: result: Building GTK3 theme 3.24
    configure:3040: result: Building GNOME Shell theme 3.38
    configure:3138: result: Building Cinnamon theme 4.6
    ```

- [x] Test whether the issue also appears with default themes (e.g. Adwaita for gtk and gnome).

    Doesn't reproduce under default shell theme.

### Details

* Arch Linux
* gnome-shell 3.38.1-1
* arc-theme @ 0c53316 w/ [font-size-patch](#font-size-patch)
* Screen resolution: 2560x1440

See [screencast](https://keynfawkes.ams3.digitaloceanspaces.com/Public/Screencast%20from%2008-10-20%2011:56:35.webm).

At the end of _leave overview_ animation windows noticably "jump" into place. At the start of _enter overview_ animation there's similar jump though less pronounced.

Just to be sure I ran a fresh shell once more with all extensions disabled (except _user themes_ obviously), the effect is still the same. To make screencast recording clearer I slowed down animations 3 times with [Impatience](https://extensions.gnome.org/extension/277/impatience/) extension.

#### font-size-patch

Added for completeness, hovewer I reproduced the issue without it applied as well.

```
diff --git a/common/gnome-shell/3.38/sass/_common.scss b/common/gnome-shell/3.38/sass/_common.scss
index 51f0bca..2068c9d 100644
--- a/common/gnome-shell/3.38/sass/_common.scss
+++ b/common/gnome-shell/3.38/sass/_common.scss
@@ -33,7 +33,7 @@ $asset_path: assets;
 //
 // Globals
 //
-$font-size: 11;
+$font-size: 9;
 $_bubble_bg_color: opacify($osd_bg_color,0.25);
 $_bubble_fg_color: $osd_fg_color;
 $_bubble_borders_color: transparentize($osd_fg_color,0.8);
```

---

**EDIT 1**: Added screen resolution, just in case.

**Comment by jnsh** [comment]
Thanks for the report. I had actually noticed this myself, but didn't even consider that it could result from the shell theme. I'll try to figure out a fix..

**Comment by drakkar1969** [comment]
I have the same issue. It appears to be caused by a `padding` property in the `#overview` section of the gnome shell SCSS.
I would be happy to submit a PR for this, if ok by you @jnsh

**Comment by jnsh** [comment]
> I would be happy to submit a PR for this, if ok by you @jnsh

That would be great. Thanks :)

**Comment by keynslug** [comment]
Nice work!
