### ISSUE TITLE
Wrong calender color in notification menu, Gnome 3.38.1

### ISSUE THREAD

**Issue by hmmSalat** [jnsh/arc-theme#90]
Hey,

first of all: thanks for maintaining this great theme!

Since updating to Gnome 3.38.1 the calendar notification is using the wrong color:
![screenshot](https://user-images.githubusercontent.com/48926955/95610199-35c25b00-0a60-11eb-9dfc-a0710d315acd.png)

**Comment by jnsh** [comment]
This has already been fixed.
Please see https://github.com/jnsh/arc-theme/issues/84#issuecomment-704524815.
