### ISSUE TITLE
Theme in flatpak too.

### ISSUE THREAD

**Issue by jairoraiol** [jnsh/arc-theme#94]
Hi!
I would like to have this theme in flatpak too.
Currently, on Flathub, there is no Lighter variant.

Thank you.

**Comment by jnsh** [comment]
Hello,

I don't provide any precompiled packages. You should request for the flathub packager to update the package.

There was [a recent issue ](https://github.com/jnsh/arc-theme/issues/86)about the same matter, and looks like the reporter opened an issue for the flathub package, but there has not been any response yet: https://github.com/flathub/org.gtk.Gtk3theme.Arc-Dark/issues/2
