### ISSUE TITLE
Window buttons disappearing

### ISSUE THREAD

**Issue by DonaNobisPacem** [jnsh/arc-theme#98]
Hi, coming off from a fresh Arch installation with Cinnamon. I've noticed that in some apps, the window buttons (close, minimize, maximize) disappear. This happens when I select any of the Arc themes under `Themes > Controls`. They're still accessible, as they still function if I click in the approximate area of where they should be, but they're just not visible. I'm also not sure as to why some applications aren't affected and some are. Here are some sample screenshots I've taken.

**System specs:**
```
OS: Arch Linux 
Kernel: x86_64 Linux 5.9.6-arch1-1
DE: Cinnamon 4.6.7
WM: Muffin
WM Theme: Arc-Dark (Arc-Dark)
GTK Theme: Arc-Dark [GTK2/3]
Icon Theme: Numix
```

**Window buttons gone**
![Screenshot from 2020-11-09 20-24-52](https://user-images.githubusercontent.com/2908239/98540958-ab248400-22c9-11eb-864f-38d023128348.png)
![Screenshot from 2020-11-09 20-25-06](https://user-images.githubusercontent.com/2908239/98540965-acee4780-22c9-11eb-8b3b-dcd47c6aed48.png)
![Screenshot from 2020-11-09 20-18-23](https://user-images.githubusercontent.com/2908239/98540546-115cd700-22c9-11eb-951c-52a82ac351a1.png)

**Window buttons still there**
![Screenshot from 2020-11-09 20-25-36](https://user-images.githubusercontent.com/2908239/98541087-d5764180-22c9-11eb-90c1-3c511ec40ef7.png)
![Screenshot from 2020-11-09 20-26-48](https://user-images.githubusercontent.com/2908239/98541204-08203a00-22ca-11eb-8c5c-44b54f1527c0.png)

**Comment by jnsh** [comment]
Do you have any custom styling in your user's `~/.config/gtk-3.0/gtk.css`, and does this happen with newly created user with no preexisting user configuration (i.e. completely empty home directory)?

**Comment by DonaNobisPacem** [comment]
I made a new user just to test it out, and it turns out that one has no issues! I compared the contents of `~/.config/gtk-3.0/gtk.css` for both my users, and seeing that the new one has it empty, I did the same for the other. Now it looks like it's been fixed as far as I can tell.

As for the installation of the themes, I used `yay` to install `arc-gtk-theme`.

**Comment by jnsh** [comment]
In that case, it sounds like your problem resulted from whatever you had in the `gtk.css` file, and not from the installed theme.

Thanks for reporting a potential bug nevertheless. Closing.
